### ISSUE TITLE
FE Setup, Testing, and Data Management (local, remote)

### ISSUE THREAD

**Issue by W3stside** [gnosis/dex-react#1]
Dmitry (@Velenir) and I are recommending the following approach:

### Frontend code/styling:
1. React 16+ with hooks
2. [StyledComponents](https://www.styled-components.com/docs)
3. Typescript

### Data Management (Local, Remote)
1. Remote: [Apollo-React](https://www.apollographql.com/docs/react/why-apollo/) - GraphQL management inside React (remote and local data)
2. Local: [Apollo-React](https://www.apollographql.com/docs/react/why-apollo/#combine-local--remote-data) local state management

### Testing 
1. Business logic/API/External data testing via [Jest](https://jestjs.io/)
2. Using mock data via [Apollo-React](https://www.apollographql.com/docs/react/recipes/testing/#mockedprovider) MockedProvider

Anxo @anxolin suggested creating a discussion space to iterate over possible tech stack before moving forward. Please leave feedback, questions, concerns here.

**Comment by anxolin** [comment]
Should we aim then to create some PRs, related to this issue to define a basic app with the main structure, that can connect to a wallet (I'm guessing we want to use metamask and wallet connect, and safe) and incorporate the main technologies?

Maybe also basic things like page navigation, unit testing, data fetching.

We can try to do small PRs so they are easy to review :)
