### ISSUE TITLE
Reduce the number of calls to the node

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#1033]
It's becoming an issue! --> infura is on 🔥
Measure how many calls we do, in which use cases we do it and options to reduce it drastically

@Velenir says that:
* When connected to a wallet (like Metamask), our calls are just minimal
* Our Default Wallet just get tokens, so not a big issue there
* Issue --> Wallet connect. Probably getting the balances of tokens and keeping in sync with the exchange/contract

It need research. Probably #1031 will help!

**Comment by Velenir** [comment]
_Estimation: 4_
