### ISSUE TITLE
Improve order expiration and start of the batch

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#1052]
![image](https://user-images.githubusercontent.com/2352112/82836429-becc6180-9ec6-11ea-9b73-b1de4eb8940c.png)

As a first version it was OK, but I think it's calling for a second iteration. I would suggest to do what we meant to do in the first place 

**Order Expires In (Min)**
Allow to set an expiration in hours, days, .... 

**Order Starts In** 
Probably the same thing, plus a date/time picker, to be able to for example program a token sale.

**Default value**
Also. I think we should review again the "default" value. Currently is 2 days, but since we if we create limit orders, I would say by default should not expire. But it's difficult to tell for sure, there can be arguments supporting smaller times.

**Comment by alfetopito** [comment]
_Estimation: 4_

**Comment by anxolin** [comment]
Duplicated #1205
