### ISSUE TITLE
Order Book: Select price?

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#1053]
Can we make it easy to select a price on the graph to use in the widget?

would it make sense to select a volume too?

**Comment by alfetopito** [comment]
Price: yes
Volume: not sure

Maybe the user already picked a volume to sell and is just looking for the prices.
On the other hand, when changing the volume the price estimation is recalculated and replaces the current price. Probably a bad UX.

**Comment by alfetopito** [comment]
Duplicate of #1204
