### ISSUE TITLE
`View Order Book` displays the Order Book of the opposite pair

### ISSUE THREAD

**Issue by Rafanator** [gnosis/dex-react#1056]
After selecting a trading pair (A/B => Where A = buyToken, B = sellToken) on the `trade` tab, and clicking the `View Order Book` button, the orderbook of the opposite pair is displayed. 

The correct pair to express what is pictured below is DAI/WETH:
![Screenshot 2020-05-26 at 16 26 46](https://user-images.githubusercontent.com/26544214/82914133-6e5d0e80-9f6f-11ea-89ae-06347f6f561f.png)

When you click on `View order book`, you see the following image, which does not express the pair of the image above (DAI/WETH), but rather WETH/DAI:

![Screenshot 2020-05-26 at 16 28 33](https://user-images.githubusercontent.com/26544214/82914265-951b4500-9f6f-11ea-91cd-b70b99085a0b.png)

The correct way to express DAI/WETH in an orderbook would be the following image, which is the one I get by selecting WETH/DAI on the `Trade` page: 
![Screenshot 2020-05-26 at 16 30 58](https://user-images.githubusercontent.com/26544214/82914344-af552300-9f6f-11ea-97d7-97b0752df44b.png)

Conclusion: 

- `View Order Book` displays the Order Book of the opposite pair

Example of an orderbook for BTC/USD, from Bitmex:

![Screenshot 2020-05-26 at 16 24 12](https://user-images.githubusercontent.com/26544214/82914536-efb4a100-9f6f-11ea-98e5-e50aa8eaf523.png)

cc/ @alfetopito @anxolin

**Comment by anxolin** [comment]
@Rafanator let me know if this would close this issue: https://github.com/gnosis/dex-react/pull/1062

**Comment by Rafanator** [comment]
Looks good to me :) I Added my review on #1062

**Comment by anxolin** [comment]
Closed by #1062
