### ISSUE TITLE
Component Market

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#1064]
Create a new component `Market` to show a market name, this is to be consistent and improve how we show the markets:

* Accepts some token info: symbol + address (quoteToken, baseToken)
* Displays `BASE-QUOTE` or `BASE/QUOTE` still TBD
* We show a ellipsis if the token is too long --> we have this functionality already in the trade widget. It would be to refactor this part
* Refactor orders, trade widget, trades and Order book to be consistent and use this component

For some places we can't use markup, like in the Order Book tooltip. There we would need to use a `utils` that does the same in a "text" fashion instead of "html"

**Comment by anxolin** [comment]
@Rafanator, if we need to be consisten, what is best `BASE-QUOTE` or `BASE/QUOTE`?

My vote is `-`, cause `/` some people get confused with units (division of the two tokens)

![image](https://user-images.githubusercontent.com/2352112/83123581-60290280-a0d5-11ea-9cff-0d0d798a27bb.png)

**Comment by Rafanator** [comment]
I am indifferent. So `-` is fine.

**Comment by Velenir** [comment]
Compromise between `/` and `-` -- `BASE÷QUOTE` No? Ok :man_shrugging:
