### ISSUE TITLE
URL expires dates are not considered

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-react#1130]
If I am visiting 
https://dex.dev.gnosisdev.com/trade/OWL-USDT?sell=1000&price=1.06345&from=&expires=2881,
then I am redirected to
https://dex.dev.gnosisdev.com/trade/OWL-USDT?sell=1000&price=1.06345&from=&expires=2880

**Comment by besoeasy** [comment]
+1 checked and confirms issue

**Comment by W3stside** [comment]
@josojo  @besoeasy they are batch times meaning they must confer with multiples of 5. `nTime/5` indicating `5` minute batches

we take the passed in time and round to nearest multiple of batch time

@anxolin @alfetopito @Velenir thoughts

**Comment by josojo** [comment]
Yeah, you are right!
No bug.

One could make it maybe a little bit more clear, if one would rename it from expires to expireTimeInMin. But it is not important. If you think that this would alleviate confusion, please reopen the issue.
