### ISSUE TITLE
Submit order button is not working 

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-react#1131]
If I am visiting
 https://dex.dev.gnosisdev.com/trade/OWL-USDT?sell=1000&price=1.06345&from=&expires=2880

then I can easily place orders by clicking submit order. But when I am adjusting the order validity date to **ASAP** and end date **never**
then I am getting redirected to:
https://dex.dev.gnosisdev.com/trade/OWL-USDT?sell=1000&price=1.06345&from=0&expires=0

And then the submit order button is no longer working. No reaction is shown and no errors in the console log.

**Comment by W3stside** [comment]
This doesn't make sense- i tested this functionality when this was released extensively, something must have been badly merged at some point that broke this, will take a look

**Comment by anxolin** [comment]
I tried to follow the steps and I get the error that was already reported of the button being disabled.

@josojo can you double check if it reproduces here please? https://gateway.ipfs.io/ipfs/QmRu2XkNYQyRoZhSiULBoJZ6QRXAxYZYXxDU8cc6tZkUU6/#/trade/DAI-USDC?sell=100&price=1.00199&from=&expires=2880

**Comment by W3stside** [comment]
@anxolin @josojo fixed (here)[https://github.com/gnosis/dex-react/pull/1159]
