### ISSUE TITLE
Set default expiration as "Never expires"

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#1140]
![image](https://user-images.githubusercontent.com/2352112/85291389-bbfb6700-b49a-11ea-9d55-43a914fae900.png)

Some users gave as a feedback, that they were expecting that the limit orders don't expire.
By default, we would set "Never expires" and we let the user change that if he wants the order to expire automatically.

![image](https://user-images.githubusercontent.com/2352112/85291626-041a8980-b49b-11ea-9dab-82c437d399e0.png)

**Comment by W3stside** [comment]
@anxolin this was closed no?

**Comment by anxolin** [comment]
Yes! thanks David
