### ISSUE TITLE
Filled order are still showing up as experied:

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-react#1144]
The user `0x2E116927958482dC4E08741F55E1dFA476957fda` got their trade fully filled but then he thought that his order was canceled, as for fully filled orders, we also show the status expired:

>filled/Total 6000/600 but on the right, it says "expired"

**Comment by alfetopito** [comment]
The fix is on `develop` branch https://github.com/gnosis/dex-react/pull/1104 and should be released this week.
