### ISSUE TITLE
Spelling error in token name

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#1190]
I think we overlooked this:
![image](https://user-images.githubusercontent.com/2352112/86388967-ec5eb480-bc95-11ea-940d-95d7f64744ce.png)

I think it's not reason enough to do another hotfix. But we should address it in develop.

Also, the synthetic USD is call Synth sUSD:
![image](https://user-images.githubusercontent.com/2352112/86389044-0bf5dd00-bc96-11ea-9062-37f69e0adaea.png)

SNX seems alright:

![image](https://user-images.githubusercontent.com/2352112/86389272-5c6d3a80-bc96-11ea-92ce-f075cccc532f.png)

**Comment by Velenir** [comment]
My fault, I don't know how I completely missed it :disappointed:
