### ISSUE TITLE
Wrap ether with disconnected wallet

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#1193]
![image](https://user-images.githubusercontent.com/2352112/86463820-840fe180-bd2e-11ea-884f-d189d9721631.png)

Wrap ether button in trade page, should follow the same workflow as "deposit" or "enable". Only visible if we have a connected wallet:

![image](https://user-images.githubusercontent.com/2352112/86463903-b28dbc80-bd2e-11ea-9b3a-34aaef4185c4.png)

**Comment by alfetopito** [comment]
_Estimation: 0.5_
