### ISSUE TITLE
Issue in coinbase

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#1197]
Tested the current http://mesa.eth.link/ in "Coinbase Wallet" and 

* Connect: Works ✅
* Load balances, withdraw request, withdraw: Works ✅
* Trade page: Don't allow to create a trade ❌ - The submit button doesn't do anything
* Trade page: Issue if you are not connected ❌ - If not connected, and you try to trade, it doesn't connects or show you a message that you are not connected

I've seen many times issues with the trade page of the button not sending the transaction or doing anything when pressed for the Trade page.

**Comment by anxolin** [comment]
However in http://dex.staging.gnosisdev.com/ works. 

Is it a flaky issue or there was an issue that was fixed in staging?

**Comment by alfetopito** [comment]
> However in http://dex.staging.gnosisdev.com/ works.
> 
> Is it a flaky issue or there was an issue that was fixed in staging?

It might as well be the issue with the order validity (valid until `never`) that was fixed.
This fix is there, right?
