### ISSUE TITLE
Wrong trades count

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#1219]
![screenshot_2020-07-09_13-26-19](https://user-images.githubusercontent.com/43217/87087350-c9795680-c1e7-11ea-85df-45122eb03244.png)

Search field count says I have 5 trades, but only 3 are displayed.

Are the other 2 hidden? Invalid thus not displayed?
Not sure, have to check.

**Comment by Velenir** [comment]
Fixed by #1244
