### ISSUE TITLE
Price Estimator changes token id type in response from string to number

### ISSUE THREAD

**Issue by e00E** [gnosis/dex-react#1221]
https://github.com/gnosis/dex-react/blob/04bb98cc706d4cf0baef6b7a60d56b0dce40da59/src/api/dexPriceEstimator/DexPriceEstimatorApi.ts#L39

https://github.com/gnosis/dex-services/pull/1113 changes the base and quote token ids to be json numbers instead of json strings. I already tested that this doesn't cause problems in the frontend instance running at https://mesa.eth.link/ by pointing it to a local price estimator. Feel free to close the issue whenever.

**Comment by Velenir** [comment]
Thank you for creating this issue and testing it.
While `string -> number` change doesn't break anything now, since we don't use `baseTokenId, quoteTokenId`, to be on the safe side and not to lie to Typescript, it's better to change the types
