### ISSUE TITLE
Display token addresses in the UI

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#1233]
## Summary

As a user, I would like to be able to see addresses of the tokens displayed in the UI.

## To define

- Where to display it
- When to display it

**Comment by Velenir** [comment]
_Estimation: 1_

**Comment by Velenir** [comment]
Allow users to open a token in Etherscan. Change the token symbols by links to etherscan?

Either shortcut icon / Link in symbol / ...
