### ISSUE TITLE
Balance for tokens selector also for responsive

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#1254]
The token selector shows also the balance of the tokens:
![image](https://user-images.githubusercontent.com/2352112/88285381-42e86d00-ccef-11ea-8884-b91db7525951.png)

But not in mobile:
![image](https://user-images.githubusercontent.com/2352112/88285392-48de4e00-ccef-11ea-873a-51db6bbb2cd2.png)

There's room for it, I think we should include them

**Comment by W3stside** [comment]
wait i fixed this tho

**Comment by W3stside** [comment]
@alfetopito remember?

**Comment by W3stside** [comment]
@anxolin i think you may have been checking out-of-date develop, try again now, i don't see that problem

![Screenshot from 2020-07-24 10-36-34](https://user-images.githubusercontent.com/21335563/88374168-93b4a000-cd99-11ea-9934-1ed3ad91dcab.png)

**Comment by anxolin** [comment]
I tried in https://dex.staging.gnosisdev.com/trade/DAI-USDC?sell=0&price=0&from=&expires= wich has the 1.1.0

**Comment by anxolin** [comment]
Also, easy to reproduce:

![image](https://user-images.githubusercontent.com/2352112/88390213-38de7100-cdb8-11ea-8673-ac01d4983219.png)

**Comment by alfetopito** [comment]
> @alfetopito remember?

Sorry, bad memory.

Bad merge, maybe?

**Comment by W3stside** [comment]
> Also, easy to reproduce:
> 
> ![image](https://user-images.githubusercontent.com/2352112/88390213-38de7100-cdb8-11ea-8673-ac01d4983219.png)

@anxolin well in this pic you're not connected... staging for me no problem either

**Comment by anxolin** [comment]
> @anxolin well in this pic you're not connected... staging for me no problem either

never mind 🙈 
I checked in DEV and it's correct! thanks david
