### ISSUE TITLE
Add `Order ID` column to Trades/Orders/Liquidity orders data

### ISSUE THREAD

**Issue by W3stside** [gnosis/dex-react#1260]
As title mentions, open for discussion @alfetopito @Velenir @anxolin @Rafanator @c3rnst

**Comment by Rafanator** [comment]
Can this just be a tx of order placement? 

I think users will prefer to use something more "Ethereum-generic" than a measure that is Gnosis Protocol specific. 

Thoughts?

**Comment by W3stside** [comment]
here is the current Order ID add:
![Screenshot from 2020-07-24 11-53-06](https://user-images.githubusercontent.com/21335563/88382984-e4cc9000-cda9-11ea-8097-efc896b62224.png)

**Comment by Rafanator** [comment]
In my ideal wonder world, it shows `ID` (cause its shorter and I can see it on Dune or Graph), and when I `click on it I can get the tx` to see it on Etherscan. 

Is this somehow viable/not so much work?

**Comment by anxolin** [comment]
@Rafanator What would you be expecting to see it on Etherscan when you click on ID?
The transaction to the creation of the order? Probably is possible, although we have to load the events to find the transaction though. I agree is a good to have, but is it that important?

The reason @W3stside is experimenting on showing this id is:
- To expose the ID that is an important part, so we are closer to the protocol
- We can use it for filtering in ACTIVE and CLOSED tabs (wich is nice)
- But the biggest reason was to be able to filter by order in the trades
- The second reason that trigger this, is that users are not necesarily aware that one order can have multiple trades. Exposing the id makes it more evident. More over, it makes it easier to relate orders to trades. We had some feedback of users struggling to do that

Also this prepare the ground if we want to provide in the Order a link that would show us the Trades. That would be just a navigation to the TRADES tab that adds the order id as a filter

**Comment by anxolin** [comment]
@W3stside if you can, pls share a link to this so we can play with it

**Comment by Rafanator** [comment]
I think a `tx` is the standard, while the `id` is local of GP. Nevertheless I can live without the `tx` if it is too much work.

**Comment by alfetopito** [comment]
To display a `tx` for each order, we'll have to search through contract events to get that info.
We already do that for the trades, but just because that's the only way (for trades).
Orders on the other hand are exposed by the contract.

We might want to find all [OrderPlacement](https://github.com/gnosis/dex-contracts/blob/master/contracts/BatchExchange.sol#L96) events anyway to enrich the data, to display for instance when the order has been placed.
The contract only stores start and end dates.

**Comment by Rafanator** [comment]
An additional argument in favor of showing `tx` when users place an order is that users don't have to rely on trusting the dxDAO (or whoever hosts the frontend). 

I think we (@alfetopito and I) discussed this regarding adding token addresses to the `balances` page to reduce reliance on trust. 

Does this make sense?

**Comment by anxolin** [comment]
Showing the token address link to etherscan makes sense and I also think is good to have. It's easy so, I think we'll do it. However is not related to this PR, please @Rafanator if you want to provide any details on how you see it do it in https://github.com/gnosis/dex-react/issues/1233

Regarding the link to the order creation, as @alfetopito it means we need to fetch some info we don't have adding some extra load to the UI. It's doable, and as he says, it can also bring interesting information like when was an order created. 
We agree that is good to have, just considering the effort probably we will want to do this one after some other more relevant ones (like improving the selection for the quote token)

**Comment by anxolin** [comment]
> @W3stside if you can, pls share a link to this so we can play with it

^^^

**Comment by W3stside** [comment]
https://github.com/gnosis/dex-react/pull/1261

do draft PRs build to PRaul?

**Comment by alfetopito** [comment]
> #1261
> 
> do draft PRs build to PRaul?

Yup

**Comment by W3stside** [comment]
https://pr1261--dexreact.review.gnosisdev.com/
