### ISSUE TITLE
Balances for WETH are being truncated

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#1294]
In the example, instead of `1,336.6604 WETH` shows `,336.6604 WETH`

![image](https://user-images.githubusercontent.com/2352112/89155543-51454d00-d569-11ea-84fa-bf0ec4b40086.png)

**Comment by Velenir** [comment]
Can this be a css overflow issue, instead of formatting issue?

**Comment by Velenir** [comment]
It was CSS all along

**Comment by Velenir** [comment]
Closed by #1314
