### ISSUE TITLE
Price suggestion area redundant + too big

### ISSUE THREAD

**Issue by Rafanator** [gnosis/dex-react#1296]
This is feedback collected from Crypcat:

![photo_2020-08-03 11 35 52](https://user-images.githubusercontent.com/26544214/89170786-742f2b80-d580-11ea-84a0-db96a2c58f92.jpeg)

A) Section marked with red arrow states that USDT should be on top (it is too squeezed in)

B) Section marked with numbers (1,2,3) stated that it is redundant to have so many toggle switches and prices

My suggestion to solve B) -> show just the quote token for the price (in this case, USDT). 

Note: In this section, pairs marked with `2` and `3` are wrong. It should be `DAI/USDT` as we are selling USDT to buy DAI.
          The section marked with `1` correctly states `USDT per DAI`.

**Comment by alfetopito** [comment]
> Note: In this section, pairs marked with 2 and 3 are wrong. It should be DAI/USDT as we are selling USDT to buy DAI.
The section marked with 1 correctly states USDT per DAI.

I'm pretty sure I fixed that. Which version did he test this on?

**Comment by Rafanator** [comment]
It was this one http://dex.staging.gnosisdev.com and **correct**, you have fixed it.

<img width="494" alt="Screenshot 2020-08-05 at 13 27 29" src="https://user-images.githubusercontent.com/26544214/89407686-7f6c8d80-d71f-11ea-8237-549505e46406.png">

I guess the rest will relate to how we show prices. IMO we should display:

`0.98838` USDC

Instead of

`0.98838` DAI/USDC

What do you think? Also maybe not the best place to continue this discussion as we have our doc? Let me know what is the best place for you!

**Comment by alfetopito** [comment]
> <img alt="Screenshot 2020-08-05 at 13 27 29" width="494" src="https://user-images.githubusercontent.com/26544214/89407686-7f6c8d80-d71f-11ea-8237-549505e46406.png">
> 
> I guess the rest will relate to how we show prices. IMO we should display:
> 
> `0.98838` USDC
> 
> Instead of
> 
> `0.98838` DAI/USDC
> 
> What do you think? 

My concern with this is regarding the inverse. Because by default we show the sell price, which is fine to see only *USDC*:

![screenshot_2020-08-05_10-14-10](https://user-images.githubusercontent.com/43217/89442932-73bf9d80-d704-11ea-97b3-adfae71f4ad5.png)

But when we invert, it feels weird to see: `... price for selling DAI XXX DAI `

![screenshot_2020-08-05_10-14-26](https://user-images.githubusercontent.com/43217/89442944-77532480-d704-11ea-9ee6-4124740708d9.png)

What if, considering your proposed change, the sentence is also inverted:

From: 
- regular: `... price for selling X DAI: Y USDC`
- inverted: `... price for selling X DAI: 1/Y DAI`

To:
- regular: `... price for selling X DAI: Y USDC`
- inverted: `... price for buying 1/X USDC: 1/Y DAI`

Or would that make it worse?

> Also maybe not the best place to continue this discussion as we have our doc? Let me know what is the best place for you!

This is a good place for concrete and scoped things like this.
More in depth changes we can head back to the doc.

**Comment by Rafanator** [comment]
I agree with your suggestion:


- regular: `... price for selling X DAI: Y USDC`

- inverted: `... price for buying 1/X USDC: 1/Y DAI`

One additional question for clarification:

We will only show one form (i.e `... price for selling X DAI: Y USDC`) and give the user the option to invert, correct?

**Comment by alfetopito** [comment]
> I agree with your suggestion:
> 
>     * regular: `... price for selling X DAI: Y USDC`
> 
>     * inverted: `... price for buying 1/X USDC: 1/Y DAI`
> 
> 
> One additional question for clarification:
> 
> We will only show one form (i.e `... price for selling X DAI: Y USDC`) and give the user the option to invert as in http://dex.staging.gnosisdev.com, correct?

Yes, that's the idea.

cc @anxolin

**Comment by W3stside** [comment]
@Rafanator @anxolin @alfetopito @Velenir 

https://pr1305--dexreact.review.gnosisdev.com/

**Comment by alfetopito** [comment]
> @Rafanator @anxolin @alfetopito @Velenir
> 
> https://pr1305--dexreact.review.gnosisdev.com/

To be inline with Rafa's proposal, need to drop the quote token

![screenshot_2020-08-12_09-52-13](https://user-images.githubusercontent.com/43217/90043849-8ba59d00-dc81-11ea-8884-fcebb37f7d44.png)
:point_up: cut `/USDC`
:point_down: cut `/DAI`
![screenshot_2020-08-12_09-52-23](https://user-images.githubusercontent.com/43217/90043856-8e07f700-dc81-11ea-9df1-cf8d63f9005e.png)

Also, the underlined `Buying/Selling` text has no feedback. Do we want to leave it 'highlighted' like that?
Initially it was for indicating what the tooltip was referring to.

**Comment by Rafanator** [comment]
Correct, we need to drop cut `/usdc` on top, and `/DAI` on the second, as stated above. 

Note: There is a bug not inverting the sell amount, already noted by @alfetopito

**Comment by alfetopito** [comment]
Left a comment in the PR pointing out the issue https://github.com/gnosis/dex-react/pull/1305#discussion_r470692990

**Comment by W3stside** [comment]
Closed by #1304
