### ISSUE TITLE
Too much space in `Balances` section

### ISSUE THREAD

**Issue by Rafanator** [gnosis/dex-react#1297]
Feedback from Crypcat. Spacing in the `Balances` section too large. 

![photo_2020-08-03 12 25 24](https://user-images.githubusercontent.com/26544214/89173395-80b58300-d584-11ea-9665-867a9c56136b.jpeg)

He instead suggested this: 

![photo_2020-08-03 12 25 28](https://user-images.githubusercontent.com/26544214/89173431-8b701800-d584-11ea-9efb-01392ed59939.jpeg)

**Comment by W3stside** [comment]
closed
