### ISSUE TITLE
wrapping token names in price suggestion

### ISSUE THREAD

**Issue by W3stside** [gnosis/dex-react#1304]
![Screenshot from 2020-08-05 11-43-02](https://user-images.githubusercontent.com/21335563/89398058-edf61f00-d710-11ea-918b-bfc41749bc62.png)

I suggest this:
![Screenshot from 2020-08-05 11-47-10](https://user-images.githubusercontent.com/21335563/89398440-6957d080-d711-11ea-911a-b579c3ab3de3.png)

**Comment by W3stside** [comment]
with the tooltip going next to the header after " - Onchain Orderbook Prices"

**Comment by W3stside** [comment]
@anxolin @Velenir @alfetopito thoughts?

**Comment by alfetopito** [comment]
The idea was to have more price sources, where onchain orderbook was one of them. Thus the long name.
Was never happy with the long name either.

What about rephrase the whole sentence and move the extra description inside the tooltip?

**Comment by W3stside** [comment]
Closed by #1305
