### ISSUE TITLE
strictNullCheck for TS

### ISSUE THREAD

**Issue by Velenir** [gnosis/dex-react#137]
We may need to turn `strictNullChecks` on in `tsconfig.json`
Otherwise it doesn't notify about a lot of vars that can and will break when `null | undefined`
With `strictNullChecks: true`  Ts would require a typeguard
A couple places where it bit me: 

```js
// EtherscanLink.tsx:L15
Network[networkId].toLowerCase()

// many provider checks in WalletApiImpl.tsx

```

But just casually turning it on reveals many TS error, so need a PR to deal with them

**Estimation**: 1

**Comment by anxolin** [comment]
Good for me

**Comment by Velenir** [comment]
Change `strictNullCheck` in tsconfig to true, or better yet, remove all together and add `strict: true`.
Will show lots of type errors for code that wasn't checked so strictly before.
