### ISSUE TITLE
Open question, should we round to 100 or 250

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#1410]
![image](https://user-images.githubusercontent.com/2352112/93116219-47148380-f6bd-11ea-80b2-c3d5b75aad45.png)

In this example, the service is returning 1,600 OWL, but we show 1,750 OWL

I'm wondering if we should round up just to the next 100 USD or keep it at 250 USD.

**Comment by anxolin** [comment]
Here is the PR if no-one see any issues https://github.com/gnosis/dex-react/pull/1411

**Comment by Velenir** [comment]
Closed by #1411
