### ISSUE TITLE
Issue in the liquidity strategies

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#1412]
![image](https://user-images.githubusercontent.com/2352112/93117420-19303e80-f6bf-11ea-85df-7afdf8eb4e97.png)

I'm getting this error in Rinkeby. It happens all the time. It looks like the estimation fails because it reverts. But I haven't looked into it in much detail.

In Mesa does not occur

https://pr1407--dexreact.review.gnosisdev.com/trade/DAI-USDC?sell=0&price=0

**Comment by anxolin** [comment]
Issue is with #1205 PR. Specifically this change

![image](https://user-images.githubusercontent.com/2352112/93322826-0aa76b80-f814-11ea-860d-c244b010e900.png)

**Comment by Velenir** [comment]
Fixed by #1420
