### ISSUE TITLE
Sometimes the cancel operation fails

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#1444]
Details: https://gnosisinc.slack.com/archives/CPZA1AGKY/p1600971244026700

There's an edge case in the deletion of orders that makes some transactions to fail.
If the user tries to delete an order that is expiring in the current batch, then the estimation returns less gas, since it doesn't need to modify the storage (cancelation has no effect, since it was expiring in the current batch anyways)

Then, the user sends the transaction, but before is mined, we change to the next batch. So when it is executed, it actually can delete the order. Although this transaction end up being cheaper since we get a refund, it's execution is more costly (5K for deleting the order, vs 0 of no-storange-change).

## Proposal
We could prevent this by sending some extra gas assuming the worst case (well, is best case, since the user will pay less :P ). Ideally we check if the orders may expire in the current batch, and in that case for each one expiring we add 5K extra of gas.

 For keeping things simpler, and since this operation normally doesn't make a lot of sense, and the edge case is making a transaction that has no effect to fail (so not a great issue), we could just:
- Multiply 5K by the number of IDs being deleted, and add it to the normal estimation

**Comment by W3stside** [comment]
closed by #1445
