### ISSUE TITLE
Wrong trade count

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#1470]
For address `0x424a46612794dbb8000194937834250Dc723fFa5` in xDAI. Lists 1 trade, but the count shows 2.

![image](https://user-images.githubusercontent.com/2352112/94924287-857fb000-04bd-11eb-88f2-9f2bd3382ffd.png)

**Comment by elitedev1314520** [comment]
I would like to help with some issues.
Is there anyone I can chat with for this?

**Comment by anxolin** [comment]
@elitedev1314520 you can reach me (anxolin#6735) in Discord https://discord.com/invite/M39dTHQ

**Comment by Velenir** [comment]
Closed by #1480
