### ISSUE TITLE
Detect center of zoom

### ISSUE THREAD

**Issue by Rafanator** [gnosis/dex-react#1475]
This issue tries to determine which should be the center price for the zoom. 

I have ideas for two separate cases. 

## **Bids and asks don't cross**

For this option I would take the simple path and calculate the mid market price and use it as a center. 

Mid Market Price = (Best Bid + Best Ask) / 2 

Example:

Best Bid = 90 
Best Ask = 110 
Mid Market Price = (90 + 110) / 2 = 100 

Implications -> The orderbook will be have a center at 100

##  **Bids and asks cross**

For this price, I would select the middle point between the overlapped orders. It is important to note that when volume over the overlap is uneven, it could look a bit strange, as `Bids deep in the market with uneven volume` in this [storybook](https://pr1439--dexreact.review.gnosisdev.com/storybook/?path=/story/orderbook-sample-data--bids-deep-in-the-market-with-uneven-volume) looks.  

Same formula as before = (Best Bid + Best Ask) / 2 

Best Ask = 90 
Best Bid = 110 
Mid Market Price = (90 + 110) / 2 = 100 
Note: only difference from previous examples is that best bid has the price of the best ask of the prev example, and viceversa. 

Implications -> The orderbook will have a center at 100, as the previous example. 

@anxolin Thoughts? I still need to incorporate more components related to your suggestion on leaving prices out. Lets chat about that over Zoom.

**Comment by anxolin** [comment]
@Rafanator 
My initial thoughts are:
- The two cases are in reality the same. Just middle point between ask/bid, no need to make subcases
- This is the trivial implementation. One issue I see, is they don't depend the slightest on the volume. I can easily break this by making an order with a tiny tiny amount and price 1000B

Best Ask = 90
Best Bid = 1000B
Mid Market Price = (90 + 1000B) / 2 = 5000B

**Comment by anxolin** [comment]
This PR has been superseded. I've detailed more the improvements in https://github.com/gnosis/dex-react/issues/1473 and https://github.com/gnosis/dex-react/issues/1481
