### ISSUE TITLE
Wrong token in xDAI

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#1486]
![image](https://user-images.githubusercontent.com/2352112/95105944-237eaf00-0738-11eb-8ecf-bc1a373b4b9d.png)

The orders above are the ones I have in xDAI network. However, when I first load the app, I see something very different:
* Decimals are wrong
* Tokens are wrong, my orders are wxDAI/OWL not USDC/OWL. Probably related since USDC has 6 decimals!
![image](https://user-images.githubusercontent.com/2352112/95105934-2083be80-0738-11eb-8c06-03c0b87cbb9d.png)

**Comment by Velenir** [comment]
Can this be closed?

**Comment by W3stside** [comment]
sort of - the wrong tokens still show up if DAI for example is snagged from the orders
