### ISSUE TITLE
Test connecting with WalletConnect

### ISSUE THREAD

**Issue by Velenir** [gnosis/dex-react#153]
Test connecting interaction implemented in #136 with WalletConnect wallets (Gnosis Safe, Trust Wallet, ...)

**Estimation**: 1.5

**Comment by anxolin** [comment]
Test change wallet address

**Comment by anxolin** [comment]
Test was done!
Issues were found. They are already in https://docs.google.com/spreadsheets/d/1lkoAdvPQnoqo9dYP869kPU-ZjgCDUTB7LqXpkwncubs/edit#gid=850341883
