### ISSUE TITLE
xDAI issues with Wallet Connect

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#1540]
I'm having some issues using Gnosis Safe in the web, for xDAI network.

I was able to perform all the operations, but once the transaction is mined, the app never gets to update the UI. 

Let me describe the observed behaviour for creating an order (although is the same for any other operation):
1. Connect using Wallet Connect https://safe-team-xdai.staging.gnosisdev.com/  (Apps > WalletConnect)
2. Create an order, click submit
3. A confirm dialog is shown in Gnosis Safe. I accept
4. A Metamask dialog shows up, this time for signing the transaction. I sign it
5. The transaction is mined
6. OBSERVED BEHAVIOUR: Nothing happens in the UI after the tx being mined. The spinner, continues indefinitely.

![image](https://user-images.githubusercontent.com/2352112/96477474-d66e0300-1236-11eb-8b4c-427fe3e73eb7.png)

**Comment by Velenir** [comment]
Issue in safe repo gnosis/safe-react-apps#62
