### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by Velenir** [gnosis/dex-react#157]
Update dependencies in preparation for #97
Since many dependencies will have improved integration for techniques for reducing bundle size (react-router and lazy loading for example), better update them first

**Comment by anxolin** [comment]
dependabot makes sure of this now

**Comment by Velenir** [comment]
No it doesn't.
Dependabot, afaik, updates within semver ranges from package.json

**Comment by anxolin** [comment]
> more radically

<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia2.giphy.com%2Fmedia%2FfHR0X5PiXsUSY%2Fgiphy.gif&token=radical" data-gitmeme-token="radical"><img src="https://media2.giphy.com/media/fHR0X5PiXsUSY/giphy.gif" title="Created by gitme.me with /radical"/></a>
