### ISSUE TITLE
Get a list of tokens from a TCR

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#180]
Get list of tokens from a TCR using the graph. See dependency

One implementation of a simple TCR we truffle scripts in place:
https://github.com/nicoelzer/dxDAO-Token-Registry
https://github.com/nicoelzer/dxDAO-Token-Registry/blob/master/contracts/dxTokenRegistry.sol

cc: @alfetopito

**Comment by anxolin** [comment]
Probably is the same as https://github.com/gnosis/dex-react/issues/960, should we close this one @alfetopito ?

**Comment by alfetopito** [comment]
I think this is the third step actually.
#960 is supposed to just load the tokens from the contract, and then later cross reference with the whitelisted list of tokens coming from this task

**Comment by alfetopito** [comment]
Will use the suggested DxDao contract to deploy a test rinkeby/mainnet TCR.

BTW, sent a PR for a small fix for an issue I was having https://github.com/nicoelzer/dxDAO-Token-Registry/pull/6

**Comment by alfetopito** [comment]
Deployed the contract using Truffle migrate.

Had an issue that took me awhile to figure out. After I added `networkCheckTimeout: 60000,` to `rinkeby` network I managed to deploy the contract.

Quite painful, but managed to verify the contract on Etherscan https://rinkeby.etherscan.io/address/0xbb840456546496e7640dc09ba9fe06e67c157e1b#code

Had to manually copy all dependencies, adjust the imports and upload all files manually to Etherscan to verify it.

Used the team shared account to deploy it. Will check with the team what account I can use for mainnet.

For now, the rinkeby account is enough for testing.

**Comment by anxolin** [comment]
Good Job!

That's strange about "networkCheckTimeout", never had to do that. Maybe you don't use an API Key for the connection to infura?

For the validation, it shouldn't be so difficult. The truffle contract contains all the info you need: compiler version, the deployed bytecodes, init params, ..

Anyways, nowadays it's not required to go manual on that. @Velenir did a great tool that uses Etherescan API to verify a truffle project. I think there's other project doing that now too (they copy his I assume :P )

**Comment by alfetopito** [comment]
Deployed to mainnet and verified it https://etherscan.io/address/0x1854dae560abb0f399d8badca456663ca5c309d0

Just for fun, using a different list id (`1`)

Added all tokens currently listed on the contract (on 2020-04-30, 50 tokens).
