### ISSUE TITLE
Disable TradeWidget Submit button when amounts invalid

### ISSUE THREAD

**Issue by W3stside** [gnosis/dex-react#195]
`TradeWidget`

Submit button should NOT be enabled when amounts are invalid:

![image](https://user-images.githubusercontent.com/21335563/68746867-c0ed6380-05f9-11ea-8210-ec5533f28feb.png)

**Comment by anxolin** [comment]
I think this is done on purpose.

RF 2.5 in https://docs.google.com/document/d/1lW3SQV5FAI-gDrZZAD3REunrx4TSa9nNjxHljpCFOd4/edit#

We went for @bh2smith proposal of Overridable warning :)

**Comment by anxolin** [comment]
One thing we could do to make it clear. Is to modify also the text of the button, so the user is more aware

**Comment by alfetopito** [comment]
Yes! At first I was preventing the submission but then realized the requirement was to allow submissions when over the limit, showing the warning instead.

**Comment by anxolin** [comment]
@W3stside you can decide whether to close this one, or make a proposal to improve it slightly, or reopen the discussion
