### ISSUE TITLE
Include token images in the project

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#199]
But for some known tokens it would be desirable to have already the token images so it doesn't depend on 3rd parties.

Also, the images are now not aligned, using our images we can have the logos more consistent.

These third parties would only be used as a fallback mechanism.

**Comment by anxolin** [comment]
Today Github was some time down, and the images where not loading because we use Trust Wallet github for resolving them.

This issue has been voted up in the wish list!

**Comment by alfetopito** [comment]
What do we do about dynamicaly loaded tokens (https://github.com/gnosis/dex-react/issues/960) ?

**Comment by Velenir** [comment]
So we will need to make token images statically available
Must download them locally then. But for what tokens? can start with the current tokenList.
Or piggybacking on @alfetopito's dynamic ids, can write a script that would

- Load current token list from contract (can even save to a local `tokenList.json` like we have now)
- Load token images from trustwallet repo and save them locally to `/assets`
- Run that script sometimes or, if we make it lazy/incremental,  in travis build

After that for `TokenImage` default to `src` image from `/assets` and if not from trustwallet repo

**Comment by Velenir** [comment]
> Also Gnosis Safe uses, this, maybe it's useful for us too:
> https://gnosis-safe-token-logos.s3.amazonaws.com/0x1A5F9352Af8aF974bFC03399e3767DF6370d82e4.png

We'll either need a whole lot of all possible tokens hosted there
Or will have to deal with an ugly slowish fallback `token address --> aws check --> 404 --> trustwallet repo`
Whereas with local hosting we can already check at compile time `src={localSrc || "https://github..."}`

**Comment by anxolin** [comment]
those are good ideas. My opinion is that:
- IMPORTANT: Have the tokens we have now
- IMPORTANT: Have the logic of the fallback: Get the image locally, if fails --> get image in Trust wallet --> if fails get the default icon
- NICE TO HAVE: Script that would fetch the images to our project so we can commit it easily. I understand that it's what Dima suggest here: https://github.com/gnosis/dex-react/issues/199#issuecomment-618941449
- NICE TO HAVE: Periodically run the script to include all the new images. Ideally, this should be a travis script that would run in any release/hotfix/master branch?
