### ISSUE TITLE
Define workflow for QA

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#201]
Define a basic test for QA

Should be a doc with the steps. Also, we should design it so it's simple to test in mainnet too.

**Comment by W3stside** [comment]
https://docs.google.com/document/d/1Id31QuaH6u6HeLfWYmOSSzJYGVUomMF1dxcXEteMaR8/edit#heading=h.5fr04qskznfr

**Comment by W3stside** [comment]
closed by [QA Doc](https://docs.google.com/document/d/1Id31QuaH6u6HeLfWYmOSSzJYGVUomMF1dxcXEteMaR8/edit#)
