### ISSUE TITLE
[bug] Showing wrong amounts for exchange balance on /deposit

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#228]
### Summary

Exchange wallet showing duplicated amount after overwriting withdraw request

### Steps to reproduce 
1. on a token where there's balance on the exchange of **B**, request withdraw of **X**
1. after submitting the first withdraw request of **X** and before the tx being mined, overwrite it with a request of **Y**
1. wait until withdraw is claimable (~5min)

After second request is mined, balance is: B - Y + B
It persists even after reload/re-connect the wallet

### Details
Version: https://pr224--dexreact.review.gnosisdev.com/
Address: `0x45acf82f1B9E12890e5c1854e1250a90B1E3836e`
Token: WETH (`0xc778417E063141139Fce010982780140Aa0cD5Ab`)
Total on exchange: 7
Requested withdraw of: 5
Wallet amount: 0

![weird-amounts.png](https://images.zenhubusercontent.com/54161e1014b417b8716bc5ad/5bd9e3ce-6c7d-4cbd-bf4f-2e8903af0a4e)

### Comment
That's possibly a feature, not a bug. Contract code includes ""claimable"" amount on balance, once it's ready to claim https://github.com/gnosis/dex-contracts/blame/master/contracts/EpochTokenLocker.sol#L197

We'll have to adjust what we display in the interface in this case

Although that doesn't happen when a single request is made. Probably a race condition in the contract?

**Comment by anxolin** [comment]
Would it make sense to move this issue into dex-contracts?

If this is as you describe, It looks like you found a way to increase your balance :) 
Maybe is unrelated, but I learned yesterday that they changed the requestWithdraw, now instead of overriding is doing before the previous claim. @josojo briefly explained me why, but I didn't fully understand, apparently is to prevent an attack. Not sure if this is somehow related.

**Comment by bh2smith** [comment]
I think we need more refined details about the values of `B` and `Y` here espesially in relation with their respective magnitudes. What you are suggesting here is that I could have a balance of 10, request a withdraw of 1 and then have a balance of 19 (10 - 1 + 10). Is this really the case? I will play around with this myself and look into the contract code...

**Comment by anxolin** [comment]
I understood that there's 7 in the exchange. Did a first request, then a second of 5  without waiting for the 1st one to be mined.

As a result, and this is the reported weird behaviour, the balance was 9: he thinks is 7 - 5 + 7
This was my understanding, not sure if I got it right...

**Comment by alfetopito** [comment]
The issue here is just on the representation of the exchange value at this point in time.
After claiming, the amounts are valid again.

I'll try again to get more data points and report it here.

**Comment by alfetopito** [comment]
Had a long debugging session with Ben to try and figure out what's happening. 
Using the version https://pr233--dexreact.review.gnosisdev.com/deposit/ which points to Ben's contract that's verified and easier to interact with using etherscan: https://rinkeby.etherscan.io/dapp/0x5ABefD6234e168C39b0fD3Ec3B8A40A45a09bA14#readContract

### Steps to reproduce

Starting from a fresh account:
1. Enable TUSD. Current wallet balance in test account == 65,000 TUSD
1. After enabled, deposit during the same batch (within 5 min) [1](https://rinkeby.etherscan.io/tx/0x8e64479115906133ff02f53834b49e61a450b925e751fcbd6cb7186b709aad60), [10](https://rinkeby.etherscan.io/tx/0xd2b39b4ab5cc79d9064b084222e9a9ab6aef0e59bff96c435868d2cf1724857a) and [100](https://rinkeby.etherscan.io/tx/0x0049353d82582c8c5b08f1d57b910310b830809c84aa5e059644027799ebad32) TSUD.
1. Still within the same batch (5 min), request withdraw of [2](https://rinkeby.etherscan.io/tx/0xea941aa4ed0025487632bccc7f175823c0230caa4052038b5fb4dee49bc95c5a) and [20](https://rinkeby.etherscan.io/tx/0x846086daaf8809ad625aa3d48a9c19b06e901239fd0da22036adc1d3a5a8e0dc) TUSD.
1. Wait until batch is closed and withdraw is claimable (<5 min).

### Expected result
Exchange wallet == 111
Claimable amount == 20
Wallet amount: 64,889

### Actual result
Exchange wallet == 202
Claimable amount == 20
Wallet amount: 64,889

![tusd](https://user-images.githubusercontent.com/43217/69454618-723b7a00-0d1b-11ea-9462-727a958c7dd7.png)

### Contract values:
Querying the contract directly I see the following values:
- `getPendingDepositAmount(0x45acf82f1B9E12890e5c1854e1250a90B1E3836e, 0x0000000000085d4780B73119b644AE5ecd22b376)` == 111000000000000000000
- `getPendingWithdrawAmount(0x45acf82f1B9E12890e5c1854e1250a90B1E3836e, 0x0000000000085d4780B73119b644AE5ecd22b376)` == 20000000000000000000
- `getBalance(0x45acf82f1B9E12890e5c1854e1250a90B1E3836e, 0x0000000000085d4780B73119b644AE5ecd22b376)` == 91000000000000000000

### Frontend values
On the frontend, we [do not distinguish between pending or confirmed balances, adding both values to display the EXCHANGE WALLET amount](https://github.com/gnosis/dex-react/blob/develop/src/components/DepositWidget/Row.tsx#L46).
Claim amount and wallet amount are on the other hand have the unaltered values coming respectively from contract's pending withdraw amount and wallet balance.

### Observations
1. Once the pending amount is claimed, or a new deposit is made (for example, [9 TUSD](https://rinkeby.etherscan.io/tx/0x2f8939f592d76dd1f80c3f21ce6587563ebed403df7943d2ede79bfcf2b436d3)), amounts are again properly displayed:

![tusd-2](https://user-images.githubusercontent.com/43217/69455342-13770000-0d1d-11ea-9117-bfa57742c7f5.png)

2. The issue has nothing to do with multiple withdraws nor multiple deposits overwriting each other, nor it has to do with it containing both on the same batch.

3. The issue can be observed when there is at least 1 deposit in a batch without subsequent action (withdraw/deposit) to update the balance.

4. The issue is coming from the assumption that:
  `balance` == `exchange balance` - `pending deposit` AND 
  `pending withdraw` ∈ `exchange balance` AND 
  balances are updated by the end of a batch

**Comment by bh2smith** [comment]
My working theory is that this bug will involve change in both, the smart contract and the front-end. In brief, the contract should return sufficient information for the the front end to be able to determine the correct balance at any given time. What is happening here is that users can deposit and request withdraws while the contract never makes a call to `updateDepositsBalance`. This means that certain information which would usually be purged from storage is not.


This would likely be an adjustment to `getPendingDeposit` which should return the `stateIndex` along with the amount so that the front-end has sufficient information to determine the correct state of accounts.

At this point, I don't believe there can be a better way without sending an additional transaction (i.e. `refreshBalance`).

Tagging @josojo & @fleupold

**Comment by fleupold** [comment]
> What is happening here is that users can deposit and requestWithdraw while the contract never makes a call to updateDepositsBalance

`deposit` always calls `updateDepositsBalance` (cf. https://github.com/gnosis/dex-contracts/blob/2cdcea6f507e2e2785ca468ef4c45f8eae8b4d18/contracts/EpochTokenLocker.sol#L66)

and `requestWithdraw` executes any existing claimable withdraw which would `updateDepositsBalance` (cf. https://github.com/gnosis/dex-contracts/blob/2cdcea6f507e2e2785ca468ef4c45f8eae8b4d18/contracts/EpochTokenLocker.sol#L112)

If there is no claimable withdraw, `requestWithdraw` overrides the currently pending withdraw request.

> This would likely involve a small change to getPendingDeposit which should return a pair (amount, stateIndex) rather than just amount. 

Note, that we already have `getPendingDepositBatchNumber` exactly for this purpose. We could combine the two to one function if that is useful. But in that case maybe a method that returns a triple of Deposit, Balance, Pending Withdraw for the current batch is even more useful and atomic?

**Comment by bh2smith** [comment]
> deposit always calls `updateDepositsBalance`

These calls to update balance are made on deposit which is too early to mean anything in the case of this situation.

> we already have `getPendingDepositBatchNumber`

Since we already have this for this reason, then I would propose that this bug should remain in this repo and that the contracts don't need to be changed (i.e. it is possible to extract sufficient information to display correct balances).

**Comment by anxolin** [comment]
I understand the issue comes from `getBalance` implementation

The implementation take the `currentBatchId` into account in order to return the right value.
The issue is that we show as the balance the sum of `balance + pending deposit` and this implementation counts for us as balance the un-updated balance.

In order to have the clients with their own logics, would it make sense to add the raw balance `balanceStates[user][token].balance` getter function in the same way we do with the other (i.e. `balanceStates[user][token].pendingWithdraws.amount`). This way the getter is closer to the SC and is up to the clients to implement how to display the balances

Also, or alternatively, I find ok to offer a getter that would return an array with all this data at once. At least the 3 balances as suggested by Felix since I understand that the `stateIndex` cannot be returned in the same call since it has a different type than the balances.

**Comment by bh2smith** [comment]
It appears the previous comment contains a reasonable solution to this issue, but I don't see any new Issues or PRs opened in the `dex-contracts` repo... Is somebody already doing this? Whats the plan here moving forward?

**Comment by fleupold** [comment]
> In order to have the clients with their own logics, would it make sense to add the raw balance getter function in the same way we do with the other

I think it would be hard to differentiate between the two getBalance functions (one that is taking the currentBatchId into account and one that doesn't). We don't really have a use case for accessing the balance in another batch. 

So maybe, making the `currentBatchId` logic part of the getPendingDeposit method (and thus turning the function into the behavior @alfetopito was expecting) would be the best way to go?

**Comment by alfetopito** [comment]
> So maybe, making the currentBatchId logic part of the getPendingDeposit method (and thus turning the function into the behavior @alfetopito was expecting) would be the best way to go?

@fleupold yes, I'm onboard with that idea.

**Comment by josojo** [comment]
>So maybe, making the currentBatchId logic part of the getPendingDeposit method (and thus turning the function into the behavior @alfetopito was expecting) would be the best way to go?

Then I would also use the "currentBatchId logic in the getPendingWithdrawAmount method.
```
    function getPendingWithdrawAmount(address user, address token) public view returns(uint256) {

```
I guess you guys would run there into the same issue, right?

**Comment by bh2smith** [comment]
I believe the proposal here (although I find the comments rather vague) is to have a view function which returns all the relevant information something with signature as follows:

```
function getBalanceInfo(address user, address token) returns (uint currentBalance, uint pendingDeposit, uint pendingWithdraw, uint32 depositBatchExpiry, uint32 withdrawBatchExpiry)
```

So that all the relevant information needed to reconstruct the correct balance is returned in a single function call without any possibility of the state changing between different calls to receive the information form 5 separate functions.

Does this seem to be about right @josojo, @anxolin, @fleupold? I will create an issue with this description in the contract repo. I assume the react portion of this would be to reconstruct the balance from this query, possibly in the following, pythonic, way

```py
balance = currentBalance + pendingDepositAmount * (currentBatch <= depositBatchExpiry) - pendingWithdrawAmount * (currentBatch <= withdrawBatchExpiry)
```

Note that it is possible pendingDeposit has not yet been added to the current balance, even if the batch has expired (so the boolean conditions involving current batch may not even be necessary).

**Comment by anxolin** [comment]
@bh2smith, if you create a issue, please link it here, although I think we can use this thread to agree, and then create the issue.

Your function looks good to me. 
This would allow to get the row data and let the client implement it's logic. For example some clients may decide to count the deposits already although their batchId is not expired, some other clients may prefer to pool every block and show only the applied balance, other clients may decide to fetch once and then apply the deposit when the time is right without querying again.

Your solution is not mutually exclusive for example with @fleupold  proposal, that if I understood well, we should make `getPendingDeposit` coherent with `getBalance`

Also, agree with @josojo , `getPendingWithdrawAmount` should ALSO be coherent. I think a better name would be `getWithdrawableAmount`, and show balance only if it's batchId  expired.

In essence, we should make the 3 getters to return always the same summation if we query them at a given point in time:
* The moment getBalances adds the deposit, it should disappear from pending getter
* The moment getBalances subtracts the pending withdraw, it should appear in withdrawable getter

**Comment by bh2smith** [comment]
> The moment getBalances adds the deposit, it should disappear from pending deposit getter

We need to be aware here that making changes to the state inside of our getter functions will imply that they can no longer be simple public views. The intention, I thought, was to provide sufficient information without having to send two transactions. With regards to the comment I have highlighted, this would mean that we can't make things disappear... unless, of course if you mean to simply include an if statement which returns 0 when the pending value has expired.


 > if you create an issue, please link it here, although I think we can use this thread to agree, and then create the issue.

I would very much like to create the issue, but I don't think I'll be able to do it today... @josojo do you now have a good understanding of what we should do here?

**Comment by anxolin** [comment]
> We need to be aware here that making changes to the state inside of our getter functions will imply that they can no longer be simple public views

I don't mean to modify any state. 

What about, on top of your proposal @bh2smith, sth like:

```js
function getBalance(address user, address token) public view returns(uint256) {
        uint256 balance = balanceStates[user][token].balance;
        if (balanceStates[user][token].pendingDeposits.stateIndex < getCurrentBatchId()) {
            balance = balance.add(balanceStates[user][token].pendingDeposits.amount);
        }
        if (balanceStates[user][token].pendingWithdraws.stateIndex < getCurrentBatchId()) {
            balance = balance.sub(Math.min(balanceStates[user][token].pendingWithdraws.amount, balance));
        }
        return balance;
    }

// Now we need to be coherent with the other two
function getPendingDepositBatchNumber(address user, address token) public view returns(uint256) {
        if (balanceStates[user][token].pendingDeposits.stateIndex < getCurrentBatchId()) {
               // Deposit has been already applied in getBalance (no pending anymore)
               return 0
        }
        return balanceStates[user][token].pendingDeposits.stateIndex;
    }

// Renamed getPendingWithdrawAmount --> getWithdrawableAmount
function getWithdrawableAmount (address user, address token) public view returns(uint256) {
        if (balanceStates[user][token].pendingWithdraws.stateIndex >= getCurrentBatchId()) {
            // Not withdrawable yet
            return 0
        }

        return balanceStates[user][token].pendingWithdraws.amount;
    }
```

**Comment by bh2smith** [comment]
Yes, this seems appropriate... We could even use `getWithdrawableAmount` and `getpendingDepositAmount` in the `getBalance` function...

**Comment by alfetopito** [comment]
I do have one concern here, please help me understand @bh2smith @josojo @fleupold @anxolin 

If from now on `getPendingWithdrawAmount` (or the renamed `getClaimableAmount`) will return `0` when it's ready to be claimed, how can we tell when there's an amount that is ready to be claimed but has not been claimed yet?

To exemplify what I'm thinking, let's consider the web interface:
1. User has balance of `5` and request withdraw of `5` in batchId `N`.
2. Interface displays balance `5` and pending withdraw `5`
3. On batchId `N+1`, balance is `0` and pending withdraw is also `0`.

Where did the unclaimed `5` go? How can we get this information from the contract?


I believe that's why at first Felix suggested to have this behaviour on `getPendingDepositAmount`, but not on `getPendingWithdrawAmount`. 

Pending withdraw is used separately, while pending deposit is considered part of the balance already.

For consistency sake, might be worth to make the `all info call` and keep the isolated functions with their current behaviour. What do you think?

**Comment by bh2smith** [comment]
> If from now on getPendingWithdrawAmount (or the renamed getClaimableAmount) will return 0 when it's ready to be claimed

NO! It will return zero until it becomes claimable and then it will return claimable amount (like it should). Please notice the reversed inequality.

**Comment by anxolin** [comment]
> getClaimableAmount) will return 0 when it's ready to be claimed

I think you have one point, although is the other way around. You have 0 while is not matured

While is not matured the withdraw, it still valid balance, and it's not deducted yet in `getBalance`.

**Comment by anxolin** [comment]
And the point that I take from your comment that it's true, is how do we tell now the amount that a user is withdrawing BEFORE it matures. 

We can use @bh2smith function and discard the unneeded values for sure, but maybe is not bad  to add an additional `getWithdrawingAmount`, but it starts to feel like a lot of getters :) 

```js
function getWithdrawableAmount (address user, address token) public view returns(uint256) {
        if (balanceStates[user][token].pendingWithdraws.stateIndex < getCurrentBatchId()) {
            // Now is withdrawable
            return 0
        }

        return balanceStates[user][token].pendingWithdraws.amount;
    }
```

**Comment by bh2smith** [comment]
Why not just have 

```
getPendingDepositInfo(user, token) returns (amount, maturityIndex)
getPendingWithdrawInfo(user, token) returns (amount, maturityIndex)
```

**Comment by bh2smith** [comment]
Of course the current solution we have is insufficient because there is no way of extracting the pending Withdraw amount from anywhere until it has been claimed.

**Comment by alfetopito** [comment]
> > If from now on getPendingWithdrawAmount (or the renamed getClaimableAmount) will return 0 when it's ready to be claimed
> 
> NO! It will return zero until it becomes claimable and then it will return claimable amount (like it should) when it becomes claimable. Please notice the reversed inequality between the `getBalance` which shows pending amounts while they are still pending, which then passes over the amounts to the other functions once they are no longer pending.

Ah, my bad. It's indeed the opposite of what I understood: `balanceStates[user][token].pendingWithdraws.stateIndex >=  getCurrentBatchId()`

>  I am going to commandeer this problem, and will ping us all back when its ready for review.

Ok, I'll wait for it to be ready :)

:crossed_fingers:

**Comment by alfetopito** [comment]
Smart contract is being updated. Need to adapt frontend balance/deposit/withdraw mock/implementation for new version https://github.com/gnosis/dex-contracts/pull/372#pullrequestreview-327649909

**Comment by anxolin** [comment]
Created new issue: https://github.com/gnosis/dex-react/issues/299

**Comment by anxolin** [comment]
Now the contracts are updated and this one should be doable.

I've created this other issue to adapt the get balances/maturity to the app, after that we are good to go for solving this issue:
https://github.com/gnosis/dex-react/issues/332
