### ISSUE TITLE
[bug] can claim multiple times

### ISSUE THREAD

**Issue by Velenir** [gnosis/dex-react#229]
[claiming](https://github.com/gnosis/dex-react/blob/a8a2ae0765c3e9a97956fda6414ad5f6260f63e2/src/components/DepositWidget/Row.tsx#L78) prop becomes false soon after clicking it, before claim tx actually goes through
That allows to click it several times.

This happens because we don't separate on-chain state from local state very well when it comes to token balances:
 

1. `claiming` first comes from from [`useTokenBalance`](https://github.com/gnosis/dex-react/blob/10b1f16d7c0465c3955c628903794d26fb4ff329/src/hooks/useTokenBalances.ts#L51) with `false` by default
2.  then it's set to true in [`useRowActions`](https://github.com/gnosis/dex-react/blob/10b1f16d7c0465c3955c628903794d26fb4ff329/src/components/DepositWidget/useRowActions.tsx#L137) on `claim()`
3.  then on new block new balances come from `useTokenBalances` which override `claiming`

Ways to solve as I see them:

- don't update balances before tx is mined -- BAD, balances should be updated dynamically, irrespective of any tx
- don't keep `claiming` together with balances, even putting it super close to the metal, so to say, would work, in `<Row/>`
```ts
// Row.tsx::L78
<RowClaimButton
  className="success"
  onClick={() => onClaim.then(toggleLocalClaiming, toggleLocalClaiming)}
  disabled={claiming}
>
```

Disadvantage of the latter way, though I believe it's the right way, -- rewriting state logic for `DepositWidget, Row, useTokenBalances, useRowActions, who knows what else`

Thoughts?

**Comment by anxolin** [comment]
Good catch, and nicely exposed.

Is this why the action's loadings are not working?
I understand that we have similar problems with other actions.

> don't keep claiming together with balances
You mean to separate the pure data fetched from the UI data?

Would it be sufficient to:
* Make `tokenBalanceDetails` expose (return) a `setHighlighted`, `setEnabled`, `setClaiming` function? Then when refreshing, is only updating the token data.
* `useRowActions` use this setters

**Comment by Velenir** [comment]
> You mean to separate the pure data fetched from the UI data?

Yes
> Would it be sufficient to:

Maybe
