### ISSUE TITLE
[bug] Tokens disappear

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#234]
### Summary

Tokens disappear from list on /deposit at random, and come back as well.

Version: https://pr233--dexreact.review.gnosisdev.com/, https://pr232--dexreact.review.gnosisdev.com/

### Steps to reproduce

1. Connect using Metamask. 
2. Keep the page open. 

Occasionally, tokens disappear. And come back at will

![disappearing-tokens](https://user-images.githubusercontent.com/43217/69464382-0fee7380-0d33-11ea-9ded-9599b80533f0.png)

### Logs 

```
MetaMask - RPC Error: header not found 
Object { code: -32000, message: ""header not found"" }
inpage.js:1:79956
```

```
Error for 
Object { name: ""Paxos Standard"", symbol: ""PAX"", decimals: 18, address: ""0xBD6A9921504fae42EaD2024F43305A8ED3890F6f"", addressMainnet: ""0x8E870D67F660D95d5be530380D0eC0bd388289E1"", image: ""https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x8E870D67F660D95d5be530380D0eC0bd388289E1/logo.png"" }
 0x45acf82f1b9e12890e5c1854e1250a90b1e3836e 0x5ABefD6234e168C39b0fD3Ec3B8A40A45a09bA14
```

**Comment by anxolin** [comment]
Never happened to me. Looks weird!  
Looks like it's not easy to reproduce...

**Comment by alfetopito** [comment]
Tried to reproduce on latest version (https://dex.dev.gnosisdev.com/deposit) and I can't see it any more.

Guess an issue with that branch we're testing.

Will close for now and re-open in case it's observed again.
