### ISSUE TITLE
Display time remaining in Batch

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-react#235]
There is an exposed public view in the smart contracts `getSecondsRemainingInBatch` (linked below and copied for convienience) which could be used to display current Batch ID and also the amount of time left in the batch. I imagine several users would be happy to know this... if they care about putting in orders at the very last minute or something. It would also give users an impression of when their pending state of accounts would no longer be pending.

No preference on where this should be... perhaps at the top of the page to be visible from both "trade" and "wallet" pages.

https://github.com/gnosis/dex-contracts/blob/ed31186a2bb1776a27b28644595450da0000dcd7/contracts/EpochTokenLocker.sol#L179-L184

```js
/** @dev used to determine how much time is left in a batch
  * return seconds remaining in current batch
  */
function getSecondsRemainingInBatch() public view returns(uint256) {
    return BATCH_TIME - (now % BATCH_TIME);
}
```

**Comment by anxolin** [comment]
We had a requirement for this. It's a good idea, although I don't think the web users will be trading at last second of the batch. Batches are not that long compared to the mining time. 

Anyways, I still think is not bad to show that to make the protocol more transparent. I had ideas also for the future-future I would love to refine, on displaying the current/previous/next batch on top of the history of all previous batches along with the countdown thing too

**Comment by anxolin** [comment]
@bh2smith u gave me a thumbs down ;) 

We are gathering ideas on how to improve the interface, Michel is working on them, we can review his designs and give him further input. The trading interface for now doesn't make the user very aware of the batch time. We have the idea of having a separate UI for the protocol in the future that makes the protocol more transparent.

A super early idea would be:
![image](https://user-images.githubusercontent.com/2352112/73168540-4dd49300-40fa-11ea-8f5e-e8a0fbd2031c.png)

**Comment by bh2smith** [comment]
Very cool @anxolin! I have reverted my thumbs down to a thumbs up
