### ISSUE TITLE
Update claim confirmation modal

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#242]
## Summary

The contract no longer works as we first assumed when overwriting a pending request withdraw.

Now, when the user wants to overwrite a pending withdraw request, the pending amount will be withdrawn to his wallet under the condition: the pending withdraw is no longer pending; at least 5 min (one batch) has passed since the user requested the previous withdraw.

## Proposal

1. Keep the same overwrite modal when requesting a new withdraw **within the same batch**
2. Display a different overwrite when requesting a new withdraw **in another batch**, saying:
  
  _Your pending withdraw of {pendingAmount} {symbol} is ready for claim. Be aware that if you create a new request, the pending amount will be claimed into your account_
  _The new withdraw request will remain pending until the next batch as usual_
  _No amount will be lost. Both operations (claim and new withdraw request) will be performed in a single transaction_

**Comment by anxolin** [comment]
I like the idea! I'll go and find the PR on why they did this change in the SC to understand why, before we change anything

**Comment by anxolin** [comment]
Relevant PR: https://github.com/gnosis/dex-contracts/pull/233

Okay, it seams it was done to prevent a bit of an edge case, where one evil solver would create a big withdraw request, but on his optimization consider that the funds that are not available (because of the withdraw) are available, cause he plans to cancel it last minute so his solution has and advantage over the other solvers.

**Comment by c3rnst** [comment]
I am wondering if we should make it this complicated for the user (in above mentioned case 2.). An amount ready for claim cannot be used differently and I would think that we could do this even automatically without letting the user know. Or maybe just a super simple overwrite like "By sending this withdraw request, you will automatically receive all claimable amounts back to your wallet".

**Comment by c3rnst** [comment]
Maybe even the overwrite modal for 1. is a bit complicated (as it also says "you'll have to wait again" but effectively if it's overwritten, no extra time is added). I would simply say "You have a pending withdraw request. Sending this one will overwrite the pending amount. No funds are lost"). What do you think? In either case it's all fine as it's a first version to test :)

**Comment by alfetopito** [comment]
# Message for case `1`:
The ~striked text~ will be removed, since there's no extra waiting time:

---

## Confirm withdraw overwrite

> There is already a pending withdrawal of 0.1 TUSD. If you create a new request, it will delete the previous request and create a new one.

> No funds are lost if you decide to continue.~, but you will have to wait again for the withdrawal to be consolidated.~

Do you wish to create a new withdrawal request that replaces the previous one?

Cancel | Accept

---

OR, simplify the message further as Chris suggests:

---

## Confirm withdraw overwrite 

> You have a pending withdraw request. Sending this one will overwrite the pending amount. No funds are lost

Cancel | Accept

---

# Message for case `2`:
I agree this is not a big deal user but I still think we need to tell the user somehow what's happening as this might not be the expected behaviour.

We could do a Toast info notification, such as: 

![toast](https://user-images.githubusercontent.com/43217/69649947-addb8a00-1022-11ea-8a38-3b9c63895ddc.png)

Or a modal as initially proposed, with simpler content as proposed by @c3rnst 

---

## Please note

> By sending this withdraw request, you will automatically receive all claimable amounts back to your wallet.

Cancel | I understand

---

**Comment by c3rnst** [comment]
I would do "Cancel" and "Continue" as the two options in both cases 1 and 2 to be fairly similar. Also, both suggestions for 1 and 2 are super fine, I always prefer the shorter and simpler one :)

**Comment by alfetopito** [comment]
You can check the messaging live on https://pr244--dexreact.review.gnosisdev.com/

**Comment by anxolin** [comment]
Sorry for arriving late to the conversation @alfetopito, @c3rnst , I like the new messages, and I think it's fine to leave it like this, however I want to point out that it can be confusing too this messages:

![image](https://user-images.githubusercontent.com/2352112/69818935-2185be80-11fe-11ea-92ea-5b17aeae288f.png)

I know what it means exactly, but is it possible that an user would think that he will get the tokens he is requesting right now directly into his wallet? Can this be misleading?

**Comment by c3rnst** [comment]
I thought that this was the case.
