### ISSUE TITLE
User's standing orders page (responsive)

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#246]
Create a mobile friendly version of the orders. Ideally we would have the mocks for this.

**Comment by W3stside** [comment]
@anxolin are we creating the mocks or is this outsourced? if we are making them, what is the current procedure for this?

**Comment by alfetopito** [comment]
@W3stside the creation of the mocks is tracked on this issue https://github.com/gnosis/dex-react/issues/253.

This task is to implement that

**Comment by anxolin** [comment]
Also, we are trying to decide which software to use for making the wireframes, let us know if you like any tool more than the other. 

Ideally we would like to allow anyone in the team to make a proposal using it, and also to make small modifications or comments on other's proposals

Some of the options we are exploring:

* https://balsamiq.com
* https://www.figma.com
* https://www.sketch.com
* https://zeplin.io/
* https://www.invisionapp.com/

**Comment by alfetopito** [comment]
Another requirement for the tool is to either:
- Be natively available on linux/mac/windows OR
- Provide a fully functional web interface

(So far I haven't figured out how to use InVision's web interface, thus used Figma for #253)
