### ISSUE TITLE
Reiterate in the mockups for orders and pooling interface

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#247]
Reiterate on #188

Address comments. 

* [X] Orders: https://docs.google.com/document/d/1JGLGRtvyMPNa2w_j6tH6KVqxAIzCh91ajQzIUdR_jxU/edit 
* [X] Pooling interface: https://docs.google.com/document/d/13TciRAwPshIym0CRinuLMW7I6-SSipitx4JMER7wfxE/edit

**Comment by W3stside** [comment]
Added a comment - looks good to me, best not to add too many things for our current scope. wdyt @Velenir @anxolin @alfetopito ?

**Comment by anxolin** [comment]
@W3stside I didn't see your comment. Is in any of these two docs? I've reiterated in both designs. Let me know if they are good to go
