### ISSUE TITLE
No feedback between enabling token and signing the tx to getting the tx mined

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#249]
Enable any token and wait for confirmation for the deposit

***Est**: 0.5

**Comment by W3stside** [comment]
@anxolin could you test #257 and tell me if it fixes what this is addressing? I think it might but I'm not sure. If it's not could you expand a bit more on what you mean here?

If it does cover it, feel free to change the PR to say it closes this issue as well, thanks

**Comment by W3stside** [comment]
closed by #259
