### ISSUE TITLE
Mock for responsive orders

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#253]
Wireframes of the orders page for small devices

**est**: 1

**Comment by alfetopito** [comment]
Proposal for displaying the list of active orders in a responsive way.

FYI, did it using an online collaborative tool called [Figma](https://www.figma.com/). 

Here's the link to this thing https://www.figma.com/file/4eBcXobXBMGgxntTto64YZ/Order-details-responsive?node-id=10%3A45

### Closed
![order details response closed](https://user-images.githubusercontent.com/43217/69830247-c68da080-11d8-11ea-9fb3-eb19117f4f01.png)

### Expanded
![order details response expanded png](https://user-images.githubusercontent.com/43217/69830246-c68da080-11d8-11ea-9544-1eb3c0e3ed32.png)

**Comment by anxolin** [comment]
I love it!  I wouldn't change anything!

**Comment by c3rnst** [comment]
Looks amazing!

**Comment by alfetopito** [comment]
Glad you liked it :)

Closing this issue. Implementation can be tracked on #247
