### ISSUE TITLE
[on hold] Wrap ETH

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#260]
We should allow to WRAP and unwrap ether easily...

Ideally integrated in the app. At least a link to somewhere we can wrap/unwrap.

**Comment by W3stside** [comment]
@anxolin separate repo module thing? or directly in `dex-react` for now? - am thinking a module thing that shows user's `WETH` balance, amount approved and allows to WRAP/UNWRAP/APPROVE

**Comment by anxolin** [comment]
We don't have a hard requirement on this. I wouldn't make a lot of effort on this. My current thinking is that even a link to a third party web would suffice for now.

For example this one, works for Rinkeby and Mainnet, MM and Wallet connect:
https://bamboorelay.com/profile/balances

In the future, we can reiterate and build maybe something more reusable as you suggest

**Comment by anxolin** [comment]
This issue is in "stand by" for now

**Comment by anxolin** [comment]
Let’s revive this issue 🦖
