### ISSUE TITLE
The app breaks when you are not in the right network

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#283]
We should inform the user that network is not supported

**Comment by anxolin** [comment]
Not that important for now, but something to handle for sure in the future. So pls bot, don't close

**Comment by alfetopito** [comment]
Just checked and there are still spectacular failures when using networks other than Mainnet and Rinkeby :see_no_evil:

**Comment by alfetopito** [comment]
Keep it

**Comment by alfetopito** [comment]
No, don't

**Comment by anxolin** [comment]
oh, my! This has been here forever! 
let's do this when we integrate with xDAO
cc/ @W3stside @Velenir
