### ISSUE TITLE
Adapt Smart Contract to last version

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#299]
Smart contract is being updated. Need to adapt frontend balance/deposit/withdraw mock/implementation for new version gnosis/dex-contracts#372

Make sure this bug is solved: https://github.com/gnosis/dex-react/issues/228

**Comment by anxolin** [comment]
@josojo, @nlordell  can you make sure you write in here the NPM version we should use when it's ready?

thanks!

**Comment by fleupold** [comment]
version 0.0.2
