### ISSUE TITLE
Refactor Styled components

### ISSUE THREAD

**Issue by W3stside** [gnosis/dex-react#303]
Lots of overlapping styles - refactor into simpler components that can be composed via

```ts
export const FlexContainer = styled.div<{
  flow?: string
  justify?: string
  align?: string
  width?: string
  margin?: string
  customStyle?: CSSObject
}>`
  display: flex;
  flex-flow: ${(props): string => props.flow || 'column nowrap'};
  align-items: ${(props): string => props.align || 'center'};
  justify-content: ${(props): string => props.justify || 'center'};
  margin: ${(props): string => props.margin || 'auto'};
  padding: ${(props): string => props.padding || '0px'};
  width: ${(props): string => props.width || '100%'};
  ${(props): CSSObject | null => props.customStyle || null}
`

export const CustomContainer = styled(FlexContainer)`
  background: #fff;
  border-radius: 10px;
  box-shadow: 3px 4px 2px -1px #0000000f;
  padding: 20px;
`
```
or something similar

Props-able styled components are also useful:

**Comment by W3stside** [comment]
open to yay or nays / feedback as I'm personally on the fence of adding so many props to, for example, `FlexContainer` which could be easily done straight through `customProps` - but on the otherhand I don't like the syntax of `customProps` object. It's strange to write string key props.

@Velenir i feel like you would have some link to an article roasting me which I need

**Comment by anxolin** [comment]
For me, one issue, is that this component would be appear in the react markup, moving the style there. We would have instead of just a hierarchy of functional components, a mix of functional and pure style components.

Another issue is that if we want to change the layout from grid to something else in an specific component (let's take TokenSelector as an instance), we would need to probably review both the styles and the markup because the markup is too coupled.

Last issue, you are adding an extra div for this.

**Comment by Velenir** [comment]
> @Velenir i feel like you would have some link to an article roasting me which I need

https://medium.com/styled-components/announcing-native-support-for-the-css-prop-in-styled-components-245ca5252feb
https://www.styled-components.com/docs/api#css-prop

**Comment by W3stside** [comment]
> For me, one issue, is that this component would be appear in the react markup, moving the style there. We would have instead of just a hierarchy of functional components, a mix of functional and pure style components.
> 
> Another issue is that if we want to change the layout from grid to something else in an specific component (let's take TokenSelector as an instance), we would need to probably review both the styles and the markup because the markup is too coupled.
> 
> Last issue, you are assuming every "user" of this layout will be a div.

For the last issue - no, that was just an example, not the complete code - can def be others. Though `divs` are the most highly functional components that can, in essence, replace most HTML components.

My main issue with the current setup is how coupled the CSS is and how hard it is to reason about and change as sometimes it needs to be done in several places. The hierarchy issue is true, though I have enabled `displayName: true` in `babelrc` for showing the name of the styled components at least. I see what you mean though.

I'm interested in hearing what @Velenir and @alfetopito have to say as well

**Comment by Velenir** [comment]
If you expect to add more css

```ts
export const FlexContainer = styled.div`
  display: flex;
// all other defaults without any computed props
`

<Flex as={if need a diff tag} css={`override or add css`}/>
```

Or props-able component if you don't expect many overrides

**Comment by anxolin** [comment]
> as={if need a diff tag}

This would solve the last of my issues, yep

> My main issue with the current setup is how coupled the CSS is and how hard it is to reason about and change as sometimes it needs to be done in several places.

I don't fully understand how this helps in this particular matter. Sure, we can set some default for a generic Flex component, but flex already have some ok defaults, so we would be saving a few lines of css tops. 
If we create this Flex components, which change you foresee we will want to make in the future that will require to go over all the flex boxes and save us time to have in a component?

I mean, you need to style also the children so I think with this approach it's possible we end up doing:
```jsx 
<Flex as={if need a diff tag} css={`override or add css`}>
<Child1 css={`override or add css`} />
<Child2 css={`override or add css`} />
</Flex>
```

This makes it a bit mixed the markup of the components and the styling of them. I see it ok for prototyping, but when we have components with lots of data properties mixed with css can became a bit messy

If you see a pattern that repeats and you can abstract it away and you can give it a nice name, this would maybe be worth it. But "Flex" sound to me to generic

**Comment by W3stside** [comment]
> For me, one issue, is that this component would be appear in the react markup, moving the style there. We would have instead of just a hierarchy of functional components, a mix of functional and pure style components.
> 
> Another issue is that if we want to change the layout from grid to something else in an specific component (let's take TokenSelector as an instance), we would need to probably review both the styles and the markup because the markup is too coupled.
> 
> Last issue, you are assuming every "user" of this layout will be a div.

Well the idea would be to have several different composable styled components beyond just the `FlexContainer` one - could extend to other elements beyond divs as well.

In regards to the React hierarchy showing styled components, enabling `displayName: true` inside `babelrc` would show the name of the pure styled componens there instead of just `StyledComponent` though I do understand this doesn't fix the issue you're bringing up.

In my honest opinion this approach makes designing much easier and similar to react props passing etc, as CSS gets super jumbled and very messy to refactor later on. 

Thoughts @Velenir and @alfetopito ? I can post more examples in a branch of how it could be used for you guys to love (hopefully) or tear apart ;)

**Comment by W3stside** [comment]
oops i didnt realise the other response went through. anyways let me consider everything being said, it's all good points

**Comment by alfetopito** [comment]
I'm 100% in favor of refactoring and abstracting away duplicated logic.
I myself have been duplicating CSS stuff in the latest `grid`s I did. While that was good for learning, I feel like the extent of styled components and css classes scattered around components will soon become, if not already, a mess to maintain.

**Comment by anxolin** [comment]
Agree, maybe in upcoming PRs we see if there's "natural refactors"

**Comment by W3stside** [comment]
old closing
