### ISSUE TITLE
Autoconnect improvement

### ISSUE THREAD

**Issue by Velenir** [gnosis/dex-react#314]
Incroporate WebSocket events into autoconnect logic when WalletConnect/walletconnect-monorepo#209 is merged and released

Related to #311

**Comment by Velenir** [comment]
So on the issue of UX/ showing connected wallet state.

As lastProvider logic is asynchronous (plus the artificial delay for WC), we have to wait somewhere:

    Before the whole App renders -- terribad
    Before Wallet component is shown -- maybe
        Show Wallet comp in Loading state -- I don't like
        Just switch to loaded state like it's doing now -- jarring
        Don't show component while loading provider

I think we can wait for WC update with new events. If the delay ends up minimal we can go with 2.iii

**Comment by anxolin** [comment]
Done by @Velenir
