### ISSUE TITLE
Review colors

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#335]
There's some colors that are a bit broken, I think we should do a full workflow reviewing all the states of the components:

For example, when claiming, the texts doesn't have contrast:
![image](https://user-images.githubusercontent.com/2352112/71245234-912a2d80-2314-11ea-8b10-74c332ec3ba5.png)

And we should review some texts like:
![image](https://user-images.githubusercontent.com/2352112/71245296-b0c15600-2314-11ea-8e35-c219cfed96e8.png)

![image](https://user-images.githubusercontent.com/2352112/71245341-c20a6280-2314-11ea-8185-3cf7c384e17c.png)

**Comment by alfetopito** [comment]
New design coming from @biocom makes this no longer relevant.

Closing.
