### ISSUE TITLE
Claimable Withdraw should be upper bounded by available balance

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-react#339]
If I create a withdraw request for a large amount, it will show that amount in the UI even though my available balance in the exchange wallet might be much smaller.

Would it make sense to "upper bound" the amount displayed by the amount available in the exchange?
<img width="1279" alt="Screen Shot 2019-12-21 at 12 05 50" src="https://user-images.githubusercontent.com/1200333/71307171-b7ba9800-23ea-11ea-9516-db0ba999cd5f.png">

**Comment by alfetopito** [comment]
I though we did that, but apparently not. Thanks for reporting it. I agree this is a better ux.

**Comment by fleupold** [comment]
I believe I used etherscan to request my withdraw. If the UI in itself doesn’t allow for this consider it low pri. 

However, how does one request an optimistic withdraw “in advance” if it’s capped at the currently available balance?

**Comment by anxolin** [comment]
Good question, we don't allow "optimistic withdraw" as we defined the user workflow for the user

Do you think we should allow it for this version? Not sure if it makes that part sense for now.

**Comment by alfetopito** [comment]
Since the UI itself does not allow this behaviour, is there still something to be done?

I'll close this issue for now. Feel free to re-open if there's any action to be taken.

**Comment by fleupold** [comment]
Note, that this issue is very related to https://github.com/gnosis/dex-contracts/issues/539

The smart contract itself doesn't allow you to read the available balance but in js you could read contract storage at the right address in order to fetch it.
