### ISSUE TITLE
Better control for invalid tokens

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#375]
Currently, when you load the web using the sell/buy params in the URL with wrong values, it defaults to one token and doesn't show an informative message to the user:

https://dex.gnosis.io/trade/0x0-0x1?sell=0&buy=0.000001

If the tokens are not valid tokens, we should display a message.
Is not valid if it's not a tradable token in the exchange.

This issue should be reviewed when we implement the addition of any token in the exchange.

**Comment by alfetopito** [comment]
Keep it open

**Comment by alfetopito** [comment]
@anxolin @Velenir still relevant?

**Comment by anxolin** [comment]
I think it's relevant. It might be that you are just not in the right network. However, it's not super important compared to our other tasks

**Comment by anxolin** [comment]
Done in https://github.com/gnosis/dex-react/pull/1182
https://github.com/gnosis/dex-react/pull/1168
