### ISSUE TITLE
Accept any address in the URL params of the trade page

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#376]
Allow to trade using any token not in the list.
Accept an address in the URL params
Verifies that the token is in the exchange. Shows an error otherwise.

Example: https://uniswap.exchange/?outputCurrency=0x1a5f9352af8af974bfc03399e3767df6370d82e4

Related:
* Handle better tokens not in the exchange: https://github.com/gnosis/dex-react/issues/375
* Allow to add any token in the token selector: https://github.com/gnosis/dex-react/issues/378
* Add token in the deposit page: https://github.com/gnosis/dex-react/issues/379

**Comment by anxolin** [comment]
An example of a dapp doing something similar: https://uniswap.exchange/?outputCurrency=0x1a5f9352af8af974bfc03399e3767df6370d82e4

**Comment by Velenir** [comment]
Closed by #866
