### ISSUE TITLE
Allow to add any token in the token selector

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#378]
Allow to add any token in the token selector.

The user pastes the address, and then:
* It verifies that the token is in the exchange. Shows an error otherwise.
* Persist in the browser the token in a different list, so it survives a refresh.

Related:
* Handle better tokens not in the exchange: https://github.com/gnosis/dex-react/issues/375
* Add token in the deposit page: https://github.com/gnosis/dex-react/issues/379
* Accept any address in the URL params of the trade page: https://github.com/gnosis/dex-react/issues/376

**Comment by W3stside** [comment]
@anxolin I'd like to take the stab at this for this sprint, thoughts? if so, where do you envision the user pasting the address? URL?

**Comment by alfetopito** [comment]
@W3stside if I recall correctly, the selector would be used. The component allows for adding arbitrary values https://react-select.com/creatable

The address from URL part is a different task

**Comment by alfetopito** [comment]
We are working on that

**Comment by anxolin** [comment]
bad bot :)

**Comment by W3stside** [comment]
closed on #760
