### ISSUE TITLE
Refactor the formatters to solve the issue reported by Ben

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#385]
Refactor the formatters, moving them from `dex-web` to `dex-js` to be able to use them in the bot.

The refactor was out of this sprint, but we have this bug, so let's try to move at list the utils there to solve it (instead of fixing the bug on code that will be discarded soon)
https://github.com/gnosis/dex-telegram/issues/86

**Comment by alfetopito** [comment]
Addressed by https://github.com/gnosis/dex-react/pull/501
