### ISSUE TITLE
Order View: Unfilled amount and limit precision

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-react#387]
When placing "spread" trades, it it likely that the user will place such trade with "infinite" sell volume and never have the order completely covered. For example here, I have placed selling 100 even though I only have 10 and I am not super excited to see this warning sign.

![Screenshot 2020-01-03 at 3 57 06 PM](https://user-images.githubusercontent.com/11778116/71730270-0253ff80-2e42-11ea-91d5-cc0f15bf6c1e.png)

Also, the ratio displayed for my order does not take more than 2 decimals into account. The order places here are at a ratio `1000:1002` but they are displayed as `100:100`

**Comment by anxolin** [comment]
For infinite amount orders (like the ones we'll create for pooling interface), we take this into account ben, so there won't be an alert on those. 

But this showing you the alert if you have not enough tokens to cover the order is a feature we added on purpose to our requirements

Related to the precision, there's a related issue, maybe we should scope the issues to one problem/suggestion and move that part there? https://github.com/gnosis/dex-react/issues/347

**Comment by anxolin** [comment]
@c3rnst any thoughts in the alert issue @bh2smith is mentioning?

**Comment by c3rnst** [comment]
I think it's exactly as you mention - when it's placed "normally" in the trade page, there can be an alert for a low deposit but shouldn't be there for huge orders placed via the strategy page...  Eventually we could have a hover that says your balance is lower than your account balance just to be clearer but I think for now this is absolutely fine...

**Comment by alfetopito** [comment]
For the low balance warning, just made a change to not display it when the order is unlimited, AKA liquidity order https://github.com/gnosis/dex-react/pull/472

**Comment by bh2smith** [comment]
Awesome sauce! You 🎸

**Comment by alfetopito** [comment]
I believe everything has been addressed:

![screenshot_2020-02-13_09-10-43](https://user-images.githubusercontent.com/43217/74434257-d3697a00-4e40-11ea-8996-8e85b2b7bdcf.png)

Higher precision, no matched amounts and no low balance indicator.
Closing
