### ISSUE TITLE
[Feature] Renew Expired Orders

### ISSUE THREAD

**Issue by bh2smith** [gnosis/dex-react#389]
This may have already been in the pipeline, but it crossed my mind that there is a `replaceOrders` function available in the smart contract which could be used to "renew" expired orders. Such a button could sit right next to the "delete" option in the screenshot below. 

<img width="691" alt="Screenshot 2020-01-04 at 21 32 34" src="https://user-images.githubusercontent.com/11778116/71771363-f0558800-2f39-11ea-9ecc-972a70d82d12.png">

**Comment by anxolin** [comment]
We've discussed this, and for some reason it didn't get too much traction for now.

I'll make sure it's consider within the list that martin is priorizating. See "Public launch" tab in https://docs.google.com/spreadsheets/d/1-_2WOLpe2bIJt48anqtSgbvW7_WsQhGJKdytPo7n5q0/edit#gid=581647550

**Comment by alfetopito** [comment]
Keep it open, we'll get there

**Comment by alfetopito** [comment]
@anxolin I'd like to have this feature, but we never got around to prioritizing it.
Should we consider in a future version or give up entirely?

**Comment by bh2smith** [comment]
Its not all that important.
