### ISSUE TITLE
[UI Nit] Sell Token Dropdown and amount input slightly off

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-react#396]
Please close if this is intended, but one of the first things I noticed when looking at the trading page is that the dropdown for the buy/sell token and the respective amount input box are vertically misaligned.

I've gotten used to it now but it bit my eye the first couple of times. 

<img width="687" alt="Screen Shot 2020-01-07 at 17 26 59" src="https://user-images.githubusercontent.com/1200333/71911008-3cd7d800-3173-11ea-9e21-06f93ca5eea1.png">

**Comment by anxolin** [comment]
There's a proposal for improvement already in place:
https://github.com/gnosis/dex-react/files/3945826/fuse_deisgn_updates.pdf 


![image](https://user-images.githubusercontent.com/2352112/71917100-98a85e00-317f-11ea-8ee2-8eb819f7e807.png)
