### ISSUE TITLE
Pooling interface: Step 1 - Select tokens

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#400]
Main component that handle the state: `spread`, `tokens`, `newStrategyTx`

Depending on the step, it would show one component or another: 4 steps

The step 1 is the selection of tokens

Details: https://docs.google.com/document/d/1yNddJk6eW1NluEh5B8IL-UghDv9tWnl0ve17SgZBf1k/edit

![image](https://user-images.githubusercontent.com/2352112/72000201-0d909c00-3243-11ea-879f-56e493e961cc.png)

**Comment by W3stside** [comment]
@anxolin @c3rnst  `The stablecoins you believe will always be around 1$` - not including this, needs to be reworded or not necessary. Will probably need a link to what stablecoins are here in this page anyways

**Comment by c3rnst** [comment]
"Select two or more stablecoins you want to include in your liquidity provision and you believe are worth 1$" ? 
What link to do refer to? As a start, we should give the options as displayed on the screenshot (should be the same links as on the trade page).

**Comment by W3stside** [comment]
OK that works, the previous wording didn't make any sense

**Comment by W3stside** [comment]
For the part that says `Please select at least 2 tokens` - what is the intended behaviour here? Can I select 3 tokens? If so, what happens on steps 2 +? What should I see

Step2: https://github.com/gnosis/dex-react/issues/401

**Comment by c3rnst** [comment]
Yes, user has to select at least two tokens.
Behaviour:
- If none or one is selected --> "Please select at least two tokens" --> Button disabled
- If two or more are selected --> "You can select more tokens or continue" --> Button enabled.
