### ISSUE TITLE
Pooling interface: Stepper component

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#404]
(lesser prio than other task in the sprint)

Details: https://docs.google.com/document/d/1yNddJk6eW1NluEh5B8IL-UghDv9tWnl0ve17SgZBf1k/edit

![image](https://user-images.githubusercontent.com/2352112/72000688-1df54680-3244-11ea-99a4-78b095894a2f.png)

Related to: https://github.com/gnosis/dex-react/issues/400

**Comment by W3stside** [comment]
part of #400
