### ISSUE TITLE
Error web3 not present

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#406]
The app doesn't load in phone. 
It looks like it's assuming that web3 is injected.

Could we do an unit test that easily checks for errors of this kind? (i.e. mount the App component and render it)

Reproduce: Open Chrome in incognito mode

**Comment by Velenir** [comment]
Can't do unit test for App component. Component too big => Too many side effect.
Can and need to do e2e test with puppeteer, eventually, but that will be quite an undertaking.
