### ISSUE TITLE
Submit Order button not clickable when using max Amount

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-react#416]
EStimation: 1.5

*Repro Steps:*
1. Load Trade Page
2. For sell token, "use max" of a token of which you have an amount with lots of decimals (number of decimals might not matter)
3. Buy 1 of any other token

*Expectation:*
- Submit Order button should be clickable

*Actually happening:*
- Submit Order button is not clickable

However when I manually change one digit in the sell amount the button becomes clickable

See attached video:  [submit-order-button.zip](https://github.com/gnosis/dex-react/files/4052817/submit-order-button.zip)

**Comment by anxolin** [comment]
It looks like, it's because the button is activated only after editing the amount in the inputs. It's a bug indeed.

We need to enable the button as long as we have a valid amount for sell/buy amounts
