### ISSUE TITLE
Allow withdraws, even if the token is not enabled

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-react#439]
![image](https://user-images.githubusercontent.com/7348154/72847265-83b0ec00-3ca2-11ea-8069-bd5d79e40419.png)

If people have done deposits via the console, it would be great to allow them to withdraw their funds via the web interface.
Currently, this is not possible, as the token is not enabled.

**Comment by alfetopito** [comment]
Duplicate of https://github.com/gnosis/dex-react/issues/407

**Comment by josojo** [comment]
Thanks
