### ISSUE TITLE
Bug Hunt (Sprint 9)

### ISSUE THREAD

**Issue by W3stside** [gnosis/dex-react#443]
Estimation: 2

Please see bug doc:
https://docs.google.com/document/d/1WCP3YNnJ6wagRL5ZhdUJ9wcmxoNXCp55jsQCeuiVDqI/edit?pli=1#heading=h.bse9jy69dtzc

And create new issues for each working on

@anxolin which should we prio? Some aren't bugs

**Comment by anxolin** [comment]
I added comments in the doc, since some of them are included in a broader task that is the redesign @biocom is working on, also moved the ones I thought it was issues to github.
