### ISSUE TITLE
Add sUSD to trading view and the liquidity view

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#461]
The order has been created already by Martin

https://gnosisinc.slack.com/archives/CC3C5SMB5/p1580213546021000

https://www.synthetix.io/
Synths are tokens that provide exposure to assets such as gold, Bitcoin, U.S. Dollars, TESLA, and AAPL within the Ethereum blockchain.

https://etherscan.io/token/0x57Ab1E02fEE23774580C119740129eAC7081e9D3
Tracks the price of a single US Dollar (USD). This Synth always remains constant at 1.

**Comment by alfetopito** [comment]
We should also (better in a different task) add the addresses for their Rinkeby contracts that provide a faucet.
When not available, deploy given contract ourselves.

**Comment by alfetopito** [comment]
On initial search, didn't find any faucet mentioned in the docs nor github repo. Created an issue asking for it https://github.com/Synthetixio/synthetix/issues/382

**Comment by anxolin** [comment]
> We should also (better in a different task) add the addresses for their Rinkeby contracts that provide a faucet. When not available, deploy given contract ourselves.

I like the idea. I think it's amazing if we show in the interface the faucelet link for rinkeby
