### ISSUE TITLE
Dynamically load token ids

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#467]
With the addition of `sUSD` on https://github.com/gnosis/dex-react/issues/461 -- which has been manually added to the contract with id `9`, but not immediately after the previous in the list (DAI with id `7`) -- the ids on https://github.com/gnosis/dex-js/blob/master/src/tokenList.json will only be valid for the current contract deployment on Mainline.

As soon as there's another Mainline deployment, or even for Rinkeby, we cannot guarantee that sUSD will be added to the contract in the same position (10th == id 9).

For this reason, we shouldn't rely on the hardcoded ids, and instead fetch the them from the contract.

**Comment by anxolin** [comment]
But, one of the data fields in the token json file is `id` wouldn't it be enough to add the right value there?

**Comment by Velenir** [comment]
Different ids on different networks

**Comment by anxolin** [comment]
> Different ids on different networks

That's right. Maybe defining the id as an object like `addressByNetwork`?

**Comment by alfetopito** [comment]
> > Different ids on different networks
> 
> That's right. Maybe defining the id as an object like `addressByNetwork`?

Well, yes. In that case we could still have a hard coded list, with the `id` bound to the network.

* Upside is that there's no client side id fetching, faster loading for the user
* Downside is that every deployment (be it mainnet or rinkeby) requires:
  1. manual changes to the file, 
  2. new dex-js npm release and 
  3. bump version on dex-react and dex-telegram. 

Not that we expect often deployments, so this might not be a big deal.

**Comment by anxolin** [comment]
Yup, it's not difficult, maybe fetching is better so adding tokens in the list is easier and we also prepare the ground for using TCRs.

Besides, thanks to the wonderful client-side catching it shouldn't be a performance issue to load the token ids, only for the first load and I don't think it's that bad (should be fast anyways)

**Comment by alfetopito** [comment]
Thoughts:

1. Ignore completely list of tokens from `dex-js`
2. Whenever not connected, default to `mainnet` list of tokens
3. Store list of tokens for each network on local storage
4. On `TokenList` constructor
    1. Load list of tokens from local storage, if any
    2. Async; Fetch [number of tokens registered in each network](https://github.com/gnosis/dex-contracts/blob/master/contracts/BatchExchange.sol#L54)
    3. If number of tokens == local list length, stop (per network)
    4. Else, fetch token details from token id = localList.length -1 until numTokensInExchange
        1. Fetch address from exchange contract
        1. Fetch symbol, name, decimals from ERC20 contract
    5. Update local storage

- Token list can start with 0 tokens and be updated async.
- Might need to update a bunch of stuff that has sync assumptions about the token list.
- Once loaded, list of tokens can be updated if adding new tokens in the UI.

**Comment by anxolin** [comment]
It sounds great. Only thing I'm hesitant is if this can be slow or not, maybe not. I think my iphone keeps deleting all local storage every time I open the browser. So this would mean, every time we open the app, we would load all the tokens from the contract, making 2 call to the node per token (one to load the token details, one for getting the address for the id)

Maybe is not an issue and 100%  worth trying!
If we experience problems, we can always find mixed approaches to boost the start up process.

**Comment by alfetopito** [comment]
> my iphone keeps deleting all local storage every time I open the browser
:scream: 

Well, we can fallback to the old list then...
As you said, let's see if that's needed.

**Comment by anxolin** [comment]
I'm thinking... not sure if we should display ALL the tokens in the contract right away. Anyone could list a scam token with a familiar symbol and still people's funds

**Comment by alfetopito** [comment]
> https://kleros.io/en/curated-list/

Do they have an API or something?

**Comment by anxolin** [comment]
It shold be on chain. For some reason their web of tokens is down now. Although I think it's this repo: https://github.com/kleros/tokens-on-trial

I don't know how the details, but I think they have different lists they mantain using a decentralize governance model, I think they have a list of tokens and even a list of stable coins.

**Comment by alfetopito** [comment]
I'm thinking about scoping it down and do that as a separated task.

- First, do only the dynamic load of token ids from the exchange, based on the hard coded list we have (this task)
- Second, dynamically load tokens from the contract, starting off from our hardcoded list (like I suggested here https://github.com/gnosis/dex-react/issues/467#issuecomment-604591406)
- Third, use kleros' list to filter out tokens (like you suggested here https://github.com/gnosis/dex-react/issues/467#issuecomment-605117194)

**Comment by alfetopito** [comment]
For the third part above, found out how to get list of tokens from Kleros.

We'll have to query [their contract](https://etherscan.io/address/0xEbcf3bcA271B26ae4B162Ba560e243055Af0E679#readContract), using [`queryTokens` function](https://github.com/kleros/kleros-interaction/blob/eb8fdb29670fc057c6d5f1e2ec30417b6ec35bce/contracts/standard/permission/ArbitrableTokenList.sol#L788)

Filter out only registered tokens, paginating the request.

We might want to store a list locally and verify the tokens async, because there are (as of now) 396 registered tokens.

**Comment by anxolin** [comment]
Nice findings!
I like the suggestions of breaking this in 3 different things.

**Comment by alfetopito** [comment]
Initial approach will not work for loading token ids (and later all tokens) on start up because I assumed all networks (for now Mainnet and Rinkeby) would be available, which is not the case.

Some investigation done on this PR https://github.com/gnosis/dex-react/pull/815

In this case I see two possible approaches:
1. Load token ids ONLY for the default networks (which now is Rinkeby but soon will be changed to Mainnet) on start, and then later when wallet is connected... (now that I'm writing doesn't seem like a good idea)
2. Load token ids once per network and only when `getTokens` is first called. Do not load it on start. (Technically, `getTokens` will be called pretty soon after app start anyway).

**Comment by anxolin** [comment]
I didn't know the plan was to load them for all the networks all at once

Yes, 2 sound good to me. And yes, I agree the default network, if the user is not connected, should be mainnet.

Deferring the load of the tokens until we actually need them for the first time seems like a good idea. It'll be right after boot anyways
