### ISSUE TITLE
Low balance indicator shouldn't be displayed for unlimited orders

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#471]
I thought I handled this, but apparently not:

![screenshot_2020-01-29_09-26-09](https://user-images.githubusercontent.com/43217/73380740-67501900-4279-11ea-892b-69d66a9d5468.png)

**Comment by anxolin** [comment]
Yep, I also notice that. I think Michel also include it in the proposal. 

Thanks for creating the issue!
