### ISSUE TITLE
Integrate contextual tooltips for helpers

### ISSUE THREAD

**Issue by Velenir** [gnosis/dex-react#476]
- Explore library options for tooltips.
- Add sample integration somewhere
- Don't actually add many tooltips before new design is ready

Library candidates: https://popper.js.org/

**Estimation: ~~2~~ 3.5**

### Update

New requirement: fill in all texts (estimation updated to reflect it)

### Dependencies

Task to get texts https://github.com/gnosis/dex-react/issues/533

**Comment by alfetopito** [comment]
Duplicate of https://github.com/gnosis/dex-react/issues/174
