### ISSUE TITLE
Add OWL, SNX and sETH to the interface

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#495]
SNX
https://etherscan.io/token/0xc011a72400e58ecd99ee497cf89e3775d4bd732f
and sETH
https://etherscan.io/token/0x5e74c9036fb86bd7ecdcb084a0673efc32ea31cb?a=0x9a4935749dbdfaf786a19df1c61a6d28b7a6cf94

**Comment by alfetopito** [comment]
For this we'll likely need the token filtering task implemented. (Can't find the issue. Was there one?)

**Comment by anxolin** [comment]
Filtering was for adding OWL for example in the telegram bot and not the web. I understand they want these tokens in the interface

Adding arbitrary tokens should be part of our next sprint, so people can make experiments easier without re-deploying the apps

**Comment by alfetopito** [comment]
> Filtering was for adding OWL for example in the telegram bot and not the web. I understand they want these tokens in the interface

Yes, but keep in mind that the same list is used on 3 places on the web: trade, wallet and liquidity.
As far as I am aware, we won't be displaying non stablecoins on liquidity page, thus the need for filtering.

David left us a TODO indicating where the filtering is currently done to prevent WETH from being listed https://github.com/gnosis/dex-react/blob/develop/src/components/PoolingWidget/index.tsx#L185

Of course, we can filter it out there as well.
