### ISSUE TITLE
Order pages stalls, if you have not placed any orders yet.

### ISSUE THREAD

**Issue by josojo** [gnosis/dex-react#508]
The pages loads simply for ever. 

I could not see any error logs in the console.

I am using brave

**Comment by alfetopito** [comment]
Is that prod version or staging?

**Comment by josojo** [comment]
it happens at http://dex.dev.gnosisdev.com/

**Comment by alfetopito** [comment]
Thanks. @Velenir just merged a fix (https://github.com/gnosis/dex-react/pull/510) which might solve this issue. Would you mind trying again?

**Comment by josojo** [comment]
It is solved! thanks, @Velenir !!!
