### ISSUE TITLE
Test version of the 24th of Feb and address possible issues

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#536]
Follow up to https://github.com/gnosis/dex-react/issues/531

Make sure we test for the injected wallet browsers:
https://gnosisinc.slack.com/archives/C58AGV3HA/p1579091615004300?thread_ts=1579091615.004300

### Estimation:
*2.5*

**Comment by anxolin** [comment]
Adding to the description:
Make sure we test for the injected wallet browsers:

https://gnosisinc.slack.com/archives/C58AGV3HA/p1579091615004300?thread_ts=1579091615.004300
