### ISSUE TITLE
Zeros and points not expressed in decimal numbers.

### ISSUE THREAD

**Issue by damiandragobetzky** [gnosis/dex-react#581]
**Description:** 
The site shows the available amount of any token without the zeros and points, leaving an incorrect and large number.

**Steps:**
-Enter https://dex.staging.gnosisdev.com/trade
-Select an available token for "Sell" 
-Observe the text below the Text Box

**Expected result:**
The available amount of each token in the wallet is shown properly, e.g. "0.0990".

**Environment:**
Google Chrome -  v80.0.3987.116

**Capture:**
![image (11)](https://user-images.githubusercontent.com/44405181/74957973-0bdff980-53e7-11ea-9324-cb9d190b897a.png)

**Additional info:**
This issue happens with every instance where decimal numbers are used in.

**Comment by alfetopito** [comment]
Thanks for reporting @damiandragobetzky 

We'll address this bug into the time slot we have for next release bug hunt https://github.com/gnosis/dex-react/issues/540

**Comment by MicaelaPesado** [comment]
Still happens on pr618--dexreact.review.gnosisdev.com Web v0.9.0-0 - Contracts v0.2.0
![2020-02-27_10h55_33](https://user-images.githubusercontent.com/44403034/75451655-b0b28780-594f-11ea-9cf2-a15f31c00690.png)

**Comment by alfetopito** [comment]
Thanks @MicaelaPesado, that's being addressed on https://github.com/gnosis/dex-react/pull/635

**Comment by alfetopito** [comment]
Fix deployed today to production.
