### ISSUE TITLE
Review styles and info for pending transaction

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#604]
Currently:
* Doesn't show the amounts of the order: 
* Doesn't show the transaction
* It's still unstyled

![image](https://user-images.githubusercontent.com/2352112/75262958-919be480-57ed-11ea-857d-7eeecc903325.png)

Current design:

![image](https://user-images.githubusercontent.com/2352112/75265187-d412f080-57f0-11ea-9dee-4ff02ac58bd4.png)

**Comment by biocom** [comment]
I can try to take care of this.
