### ISSUE TITLE
Implement enable token in Trade widget

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#611]
Implement enable token in Trade widget

![image](https://user-images.githubusercontent.com/2352112/75345492-1a258e00-589d-11ea-80c7-125bd3b88617.png)

**Comment by W3stside** [comment]
i dont see the enable button on the trade page, is this scrapped? @anxolin @biocom

**Comment by alfetopito** [comment]
@W3stside was disabled for this release, it's still there commented out.

**Comment by alfetopito** [comment]
Keep it

**Comment by Velenir** [comment]
_Estimation: 2_
