### ISSUE TITLE
Nice to have: Allow to see your full balance

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#622]
![image](https://user-images.githubusercontent.com/2352112/75360097-a04dce80-58b5-11ea-9d16-faf3455a22fc.png)

The only way you have to see your full balance in the "Balances" page is by opening the withdraw modal.

It should be more intuitive how to check the balance.

**Comment by alfetopito** [comment]
In a tooltip?

**Comment by biocom** [comment]
I think a tooltip could be good. But I also I think we could try to display more decimals (if not all) up front. The interface supports this.

**Comment by anxolin** [comment]
If we can display more decimals it would be ideal. 

We can try to display all, if it's two much, we can do for example a clickable ellipsis component

If it fits, it show all the number, if not, shows a button like ellipsis icon that if you click, it expands the number.

Would that make sense?
