### ISSUE TITLE
nit: The spread input in liquidity doesn't behave properly 

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#627]
![image](https://user-images.githubusercontent.com/2352112/75370475-6be20e80-58c5-11ea-9e38-5bdd159b1f5d.png)

It has the same behaviour as the old inputs in the deposit widget. It has leading zeros, and the behaviour is strange.

Maybe is a matter of using the hook `useNumberInput` or finding a more general solution for all our inputs.

It's feels overcomplicated what we do in the deposit widget. Maybe we can find a simpler approach and extrapolate it to all the app.

**Comment by alfetopito** [comment]
Has been addressed by @W3stside
