### ISSUE TITLE
nit: The claim label should be clickable

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#630]
![image](https://user-images.githubusercontent.com/2352112/75371844-cb411e00-58c7-11ea-95f9-88c1f7be9cb6.png)

When claiming a withdrawal, only the "amount" is clickable. I believe, the label "claim" should be too

**Comment by biocom** [comment]
@anxolin You can assign it to me, for the design part, as it requires some additional styling.

**Comment by anxolin** [comment]
The style has been addressed by @biocom already! only the click part missing

**Comment by biocom** [comment]
I think the click part is also working, last I tested.

**Comment by anxolin** [comment]
Cool, closing then. Thanks!
