### ISSUE TITLE
When entering a long number the selling textbox crashes

### ISSUE THREAD

**Issue by MicaelaPesado** [gnosis/dex-react#649]
Description:
When entering a long number on the sells box, the gap crashes, and everything is shown superimposed.

Steps:
- Go to https://dex.staging.gnosisdev.com/trade
- Enter a long number (more than 20 numbers)
- Observe

Expected result:
The page is correctly adjusted

Environment:
Google Chrome - v80.0.3987.116
![2020-02-27_12h32_12](https://user-images.githubusercontent.com/44403034/75549364-40b70680-5a0e-11ea-9e02-4b6ac0aa5050.png)

**Comment by W3stside** [comment]
@Velenir @anxolin @biocom @alfetopito I don't see this on FF using the latest master >> develop merge branch I made #671 - anyone else?

**Comment by biocom** [comment]
@W3stside It doesn't crash for me on FF. I did spot a wrapping/overflow issue (all browsers):
<img width="1841" alt="Screenshot 2020-03-02 at 10 11 22" src="https://user-images.githubusercontent.com/31534717/75661931-87a33700-5c6e-11ea-9830-76f8b0a5007c.png">

**Comment by W3stside** [comment]
yeah i see it now, good catch @MicaelaPesado

**Comment by anxolin** [comment]
This one is currently solved
