### ISSUE TITLE
Pre-fill the price

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#658]
Feedback from Martin
-------------

I think we should prefill the sell price. Even if it is something completely random like 1 or better 0.995 - it just makes it clear that when you type in “sell amount” the other receive amount is calculated.

0.995 might be a good number because for the stable/stable coins case that is sensible. For the stable-ETH usecase it does of course make no sense but we will get there in a future version.

**Comment by W3stside** [comment]
this would also solve the initial 0 validation problem reported by Marco, I am ok with it

**Comment by anxolin** [comment]
We might consider using the graph prices here. Probably it's easier and good enough estimate.

**Comment by anxolin** [comment]
Other alternative could be to get the latest available price from the contract. In any case, let's make a simple concrete proposal so we can validate it with Martin and implement it.

This initial criteria can be evolved and in the future we could have better price estimation, but let's get an initial version rolling :)

**Comment by alfetopito** [comment]
As suggested during the sprint planning, we could use a naive approach and get the value from the contract https://github.com/gnosis/dex-contracts/blob/master/contracts/BatchExchange.sol#L63

Although that price is with reference to OWL... might not be what we are looking for.

**Comment by Velenir** [comment]
So 
```js
Token1InOwl = contract.currentPrices(Token1)
Token2InOwl = contract.currentPrices(Token2)
price = Token1InOwl/Token2InOwl
```

or something?

**Comment by anxolin** [comment]
Yes, although let me double confirm today

**Comment by alfetopito** [comment]
Maybe this won't work as we expect.
Just queried the mainnet contract manually for the prices for tokens 0 to 20, and I got prices != 0 only for 3 (technically 4, but OWL will always be set): 1, 7 and 15.

@fleupold @bh2smith @josojo do we expect to have the prices set under what circumstances?

If they are only set when they have been traded in the last batch, it might not be useful directly from the blockchain. We'll need another layer like the graph.

For context, we know @fleupold is working on a service for providing the price estimation. This is just intended as a quick and naive temporary solution.

**Comment by fleupold** [comment]
> do we expect to have the prices set under what circumstances?

The smart contract only stores the prices of tokens that were traded in the most recent settlement. Thus, for a more complete picture (e.g. the last price any token was traded) we would either need to query `instance.contract.getPastEvents("SolutionSubmission", {fromBlock: 0})` (which is still fully decentralized and quite performant for now) or the Graph.

>  @fleupold is working on a service for providing the price estimation

Just to clarify this is likely not going to be its own service but more likely some js/ts code which will hopefully be usable directly in the frontend.
