### ISSUE TITLE
Input fields not readable

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#659]
![image](https://user-images.githubusercontent.com/2352112/75555202-17ad6a80-5a3c-11ea-9961-0fe2bfa8b49c.png)

![image](https://user-images.githubusercontent.com/2352112/75555225-209e3c00-5a3c-11ea-87bb-ef3970d43167.png)

Input fields are not readable

**Comment by anxolin** [comment]
@koeppelmann can you provide info about the browser you where using?
I'm seeing like this:

![image](https://user-images.githubusercontent.com/2352112/75555351-57745200-5a3c-11ea-8be6-f95f389d32ff.png)

**Comment by alfetopito** [comment]
That's the issue I talked about when on dark mode. On regular/light it displays fine.
