### ISSUE TITLE
Format amounts

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#66]
There's currently a format amount function that is used all over the app:
```js
export function formatAmount(amount?: BN): string | null {
  if (!amount) {
    return null
  }

  return fromWei(amount).toString()
}
```

This function should also:
- [ ] Have a decimal strategy (how many decimals we use in the different cases). It makes sense to use the same as the Safe: https://github.com/gnosis/safe/blob/master/specs/common/format_amounts.rst
- [ ] Take into account that the amounts are for tokens with different number of decimals

**Comment by anxolin** [comment]
@josojo @bh2smith @alfetopito @fleupold, I'm reconsidering my first approach for formatting the amounts of the app.

My original idea was to use the same safe strategy, but maybe it make sense to use 2 decimals for stable coins, and some more decimals for ether. At least as an initial approach.

What do you think?

**Comment by fleupold** [comment]
Maybe we can do whatever other apps (Compound, dydx, etc. are doing).

**Comment by bh2smith** [comment]
> 2 decimals for stable coins

I think that this is an interesting suggestion and would be happy to see that in action. 

One thing I recall from the [Fairdex interface](https://fairdex.net/auctions) was that, I always had to right0click and "inspect" the page when I wanted to exit or use all my funds in an auction:

![Screenshot 2019-09-23 at 2 04 20 PM](https://user-images.githubusercontent.com/11778116/65424207-3c594280-de0b-11e9-8df6-747a93bb719f.png)

I found this rather annoying.

**Comment by anxolin** [comment]
@bh2smith  Yes, adding relying on the title is annoying, specially on mobile you don't even have an easy option.
For exiting my plan is to be able to click on the amount, or to a MAX link, so the input is filled with all the decimals.

This PR is on how to display it in the interfaces. For inputs, I would allow any number of decimals.

**Comment by anxolin** [comment]
Some pics here: 

Compound:
![image](https://user-images.githubusercontent.com/2352112/65430229-e2ab4500-de17-11e9-9b46-e4d94181700d.png)

**Comment by anxolin** [comment]
dydx, 4 too. For any token actually, it seems an easy approach :)

![image](https://user-images.githubusercontent.com/2352112/65430392-243bf000-de18-11e9-9fee-cd3af9567b3f.png)

**Comment by anxolin** [comment]
Stable coin converter uses 2:

![image](https://user-images.githubusercontent.com/2352112/65430710-9e6c7480-de18-11e9-9a4a-b00b0fa0ae5b.png)

**Comment by anxolin** [comment]
I think the 4 decimals for all is a fine strategy for now

Sorry @c3rnst, I forgot to tag you before

**Comment by bh2smith** [comment]
> or to a MAX link

I also like this plenty!
