### ISSUE TITLE
Deposit/Withdraw modal overlay

### ISSUE THREAD

**Issue by Velenir** [gnosis/dex-react#660]
Deposit/Withdraw modal duplicates and in some cases interferes with Modali modal as described in #650 

> A proper fix would be to change not modals but content of one modal: Form -> Modali contents,; without changing overlay in-between

**Comment by anxolin** [comment]
@W3stside I think this is in the doc of tech debt. Not sure if we should have a tag for the tasks. What's the best way to handle the most important issues in that document? Issue + tag + include in different sprints.

**Comment by alfetopito** [comment]
Keep it
