### ISSUE TITLE
Order parameters aren't saved 

### ISSUE THREAD

**Issue by MicaelaPesado** [gnosis/dex-react#662]
Description:
When changing the values in the order parameters section, those are correctly saved until a transaction is made. After that, the parameters shown are the predeterminated ones. (Order starts:
ASAP- expires: in ~ 48 hours)

Steps:
- Go to pr618--dexreact.review.gnosisdev.com
- Change the order parameters 
- Execute a transaction
- Observe

Expected result:
The parameters are correctly saved for future transactions.

Actual result:
The paramenters change to the predeterminated ones after a transaction. 

Environment:
Google Chrome - v80.0.3987.116

**Comment by W3stside** [comment]
@anxolin @Velenir @biocom @alfetopito @c3rnst do we want order params to remain set as previous entries? Right now we reset form on tx sent

**Comment by alfetopito** [comment]
I think so. It makes sense to keep the values to allow an easier way to place serial orders with different token pairs. At least while we don't offer a way to place batched orders which are not part of a liquidity strategy.

**Comment by anxolin** [comment]
I think that doing the reset of the form is good, but I would just reset the amounts and price, we can keep the starts/expires

Wdyt?

**Comment by W3stside** [comment]
i think we reset everything, in the end it's less work and is similar UX. Why prioritise from and expires? seems arbitrary imo

**Comment by anxolin** [comment]
The reasoning would be to be able to create several orders with similar data. Chances are that an user that for example changes the expire time to let's say ASAP+NEVER, and want to create 3 orders, the 3 of them will probably would be ASAP+NEVER.

I would say tokens, start date, and expires are maintained. Only amounts and prices are reseted. 
However, I agree is not super important, and we can wait for more user feedback to get what's really important.

**Comment by W3stside** [comment]
closed by #784
