### ISSUE TITLE
Link devportal

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#673]
Review about and source code pages:

https://dex.staging.gnosisdev.com/about

We should include more projects there, and specially make it more visible the dev portal.

Not sure what's the best way to make user super aware of where to find the dev portal information. Maybe we can potencially add links in different places. Including the links we removed form the liquidity page (learn more about liquidity), or some context help menus.

https://docs.gnosis.io/dfusion/

**Comment by anxolin** [comment]
@c3rnst in which places you suggest to link the devportal?

We can try to come up with our own proposal, but probably you'd like to make yours.
Also related the FAQ if that should be done in the web, or in the devportal (more protocol specific) and we should just link the FAQ and some interesting pages from the dev portal.

**Comment by anxolin** [comment]
Related: https://github.com/gnosis/dex-react/issues/615

**Comment by c3rnst** [comment]
I thought we have this one to link from the liquidity page: 
https://dfusion-docs.dev.gnosisdev.com/docs/liquidity1/

**Comment by c3rnst** [comment]
It will be linked within the FAQs, which should be ready soon. Will let you know

**Comment by anxolin** [comment]
> I thought we have this one to link from the liquidity page:

No, we removed the links because we didn't have them for our release.
Okay. I will add back again the link with that link.

**Comment by Velenir** [comment]
Can this be closed as #709 is merged? Or is there something else to take care of

**Comment by anxolin** [comment]
Let's close it but after we recover the #709 lost solving merge conflicts 

git diff 64b1a3b..origin/develop -- src/components/PoolingWidget/index.tsx
