### ISSUE TITLE
UI: When orders on trade page maximized, chevron still points outward

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#676]
The chevron (**<**) should be pointing right (**>**) instead of left when maximized.

![Screenshot from 2020-03-02 12-30-15](https://user-images.githubusercontent.com/43217/75690512-c1316d80-5c81-11ea-9d0b-0c0315fc770a.png)

**Comment by Velenir** [comment]
But, but it's a left chevron, that's why it is pointing left. Now if it was a right chevron, that would be another matter.
:arrow_left: :crab: :arrow_right:
