### ISSUE TITLE
Input placeholder has weird placements

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#679]
![Screenshot from 2020-03-03 16-06-52](https://user-images.githubusercontent.com/43217/75810273-0f6d6c00-5d69-11ea-8cdd-ee6b0a4e1871.png)

Once a value is inserted, value is properly aligned.

**Comment by Velenir** [comment]
Where can I see this? Can't reproduce right away

**Comment by W3stside** [comment]
it's the placeholder value - honestly no idea in the CSS why it happens, quick fix would be no placeholder

**Comment by alfetopito** [comment]
> Where can I see this? Can't reproduce right away

On `Balances` page, click on `deposit` or `withdraw`. The values starts that way.

I'm using Firefox BTW.

**Comment by W3stside** [comment]
Closed by #711
