### ISSUE TITLE
Add CHAI

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#688]
> https://tokens.kleros.io/token/0x6ace3beea6596d4d7e2caaca20906755fbb45633e5c02284aa025a760150ac0b
We already have CHAI added as a token, would be nice to have it in the UI as well in the next release

- Look for `rinkeby` address and faucet.
- Already added to `mainnet` contract, fetch current id
- Add to `dex-js` list of known tokens

**Comment by koeppelmann** [comment]
I am afraid they have it only on Kovan:
https://github.com/dapphub/chai/tree/master/bin/conf

Token ID is: 16
Token address is: 0x06af07097c9eeb7fd685c692751d5c66db49c215
check: https://explore.duneanalytics.com/queries/1692#table
