### ISSUE TITLE
[WC] Cannot send a tx when reopening computer after sleep.

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-react#690]
I submitted an order via the frontend, before closing my laptop and going to lunch. When coming back I went back to the open tab and wasn't able to place any more orders without doing a reload (it would get stuck in the spinning "Submit Limit Order" state). I assume the ws connection was cut when I was disconnected and didn't successfully reconnect until I reloaded the entire page.

Attaching a screenshot of the console error.

<img width="1637" alt="Screen Shot 2020-03-07 at 13 38 39" src="https://user-images.githubusercontent.com/1200333/76143649-79438980-6079-11ea-92d6-806124cd7dba.png">
<img width="1634" alt="Screen Shot 2020-03-07 at 13 38 49" src="https://user-images.githubusercontent.com/1200333/76143651-7cd71080-6079-11ea-98f3-9576770d0769.png">

**Comment by Velenir** [comment]
The errors are internal to WalletConnect
I tried to update to the latest beta to see if it helps and... everything broke.
Will need to investigate separately
