### ISSUE TITLE
Wallet connect sporadic errors

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#693]
Observed on prod,staging and local dev using Chrome and Gnosis Safe (via Wallet Connect).

Once in awhile, getting the following errors (I would guess during some block updates):

![Screenshot from 2020-03-09 13-22-52](https://user-images.githubusercontent.com/43217/76254107-1c76d900-6209-11ea-95ae-576416117bb3.png)

When debug is on (via `window.toogleDebug()`), though, this is almost never seen.

_Originally posted by @alfetopito in https://github.com/gnosis/dex-react/issues/500#issuecomment-596762030_

**Comment by anxolin** [comment]
Probably related: https://github.com/gnosis/dex-react/issues/690

Also Rafa was reporting some issues in the same direction.

Rafa, you say this is resolved when you disconnect/connect again. Does refreshing the browser also solve the issue. Please, if it happens again, save the log and add it here, maybe it helps.

@Velenir could it be that the websockets setup expires? Can this be detected and solved automatically?

**Comment by alfetopito** [comment]
keep open

**Comment by alfetopito** [comment]
@Velenir anything that's potentially resolved in newer versions?
