### ISSUE TITLE
Review some design issues in trade page

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#696]
Some users report:
* Not clear to me which input fields I can amend and which ones I cannot. 
* Also, I think the formatting of the balances (here the 99.52 and the 0 are off).

![image](https://user-images.githubusercontent.com/2352112/76294733-b2673e00-62b3-11ea-95d6-e50e10c491f2.png)

**Comment by anxolin** [comment]
cc/ @biocom

**Comment by W3stside** [comment]
think this was closed by #656 - can someone confirm? @anxolin @Velenir @alfetopito

**Comment by Velenir** [comment]
Yes, looks fixed
\+ your readonly styling PR will take care of
>Not clear to me which input fields I can amend and which ones I cannot.
