### ISSUE TITLE
Pending orders and normal orders are duplicated at one point

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#718]
1. didn't have orders

2. Created an order. It was showing as pending:

![IMG_0505](https://user-images.githubusercontent.com/2352112/76743583-23ef3280-6773-11ea-8c1e-cc7698f76aab.PNG)

3. When the tx got confirmed:
![IMG_0506](https://user-images.githubusercontent.com/2352112/76743605-2d789a80-6773-11ea-840d-f8237eff2cfa.PNG)

4. Then, after 30s or so, the pending disappeared:
![IMG_0507](https://user-images.githubusercontent.com/2352112/76743656-41240100-6773-11ea-8c48-5f35da3d97a7.PNG)

**Comment by alfetopito** [comment]
This is tricky to reproduce.

I've been trying but no luck so far.

A summary on how all this is processed:

1. Tx sent; pending order with tx hash added to interface. 
2. When tx is confirmed, pending entry is removed from the interface.
3. In parallel, whenever there's a new block, we check for new txs. If there's anything new it's added to the interface.

This can only mean that for some reason, tx is being added to network on `3` before the promise is completed on `2` to remove the pending entry.

I thought about filtering out the pending txs based on the ones in the confirmed list, but they have no intersection. Confirmed txs have `order id`, pending txs have `tx hash`.
We could filter based on all order fields, but that doesn't guarantee uniquenes.

Any other ideas?

**Comment by Velenir** [comment]
> Any other ideas?

Yes other ideas. Assign reliable ids to pending orders, #723

**Comment by anxolin** [comment]
@alfetopito this is solved by your smart update PR?
Can we close?

**Comment by alfetopito** [comment]
> @alfetopito this is solved by your smart update PR?
> Can we close?

You meant me or @W3stside ?

If me, what smart update PR?

**Comment by anxolin** [comment]
I meant you. At some point, you've made a change to update the orders rather than fetch them again. 

Since I haven't seen this error in a while, I thought it might have been solved by that. But no idea.

**Comment by alfetopito** [comment]
Oh right. I haven't tested after my changes (not like I could reproduce in the first place...). But also, David's changes to handle pending orders could fix this if not already.

**Comment by anxolin** [comment]
Okay, so let's close then if it's not happening ;) 
Otherwise we can always re-open
