### ISSUE TITLE
Zoom effect in IOS

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#719]
In IOS it's doing a zoom effect when you click on one input, making the content to not fit anymore in the screen.

1. Initially looks OK

2. When you click on an input, the content doesn't fit anymore:

![IMG_0504](https://user-images.githubusercontent.com/2352112/76743876-995b0300-6773-11ea-965f-c603894bcaf9.PNG)

**Comment by Velenir** [comment]
Can't reproduce in Chrome device emulation
Makes it hard to fix

**Comment by biocom** [comment]
I'm on it.

**Comment by anxolin** [comment]
Closed by #912
