### ISSUE TITLE
Proposal: Change slightly how we present the price

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#729]
This is the current representation:
![image](https://user-images.githubusercontent.com/2352112/76952552-9136cb00-690d-11ea-9d72-22c3e52278df.png)

I think it's easier to read like this:
![image](https://user-images.githubusercontent.com/2352112/76952464-6cdaee80-690d-11ea-94e3-5b1057d53045.png)

This is being used in the CLI too.
![image](https://user-images.githubusercontent.com/2352112/76952624-ab70a900-690d-11ea-8046-e6844afa7ad5.png)

For context:
https://support.kraken.com/hc/en-us/articles/115000364388-Trading-glossary

WDYT?

**Comment by marcovc** [comment]
I personally don't like the A/B thing. I prefer "1 Something = X something else", like these guys do it here:

![uniswap](https://user-images.githubusercontent.com/624308/76958355-7d8c6400-690f-11ea-96e7-1bcf1a91f5ce.png)

**Comment by alfetopito** [comment]
I have a third suggestion. Looking at the first image:

> This is the current representation:
> ![image](https://user-images.githubusercontent.com/2352112/76952552-9136cb00-690d-11ea-9d72-22c3e52278df.png)
> 

I'd keep as it is, with the addition on top of the buy price of the label "Max buy price"

I like Marco's suggestion as well, although more verbose.

**Comment by anxolin** [comment]
Okay, what about:

![image](https://user-images.githubusercontent.com/2352112/77072664-5ce70b80-69ee-11ea-80f6-62362e59c5ba.png)

**Comment by anxolin** [comment]
Or better!

![image](https://user-images.githubusercontent.com/2352112/77073122-0a5a1f00-69ef-11ea-9fb7-c56631a8e61c.png)

**Comment by anxolin** [comment]
@rafanator what do you thing?

**Comment by Velenir** [comment]
![dex dev gnosisdev com_trade_DAI-USDC_sell=0 price=0 from=0 expires=2880](https://user-images.githubusercontent.com/5121491/77074784-62e6e780-6a02-11ea-8a0e-03784d97151f.png)

just emphasize that it's the same price but inverted?

**Comment by marcovc** [comment]
I like this one: https://github.com/gnosis/dex-react/issues/729#issuecomment-601182287
The text could be "For 1 DAI, receive at least:".

**Comment by marcovc** [comment]
No wait. We're selling DAI in the example, so:
* For 1 DAI spent, receive at least:
* For 1 USDC earned, spent at least:

**Comment by marcovc** [comment]
Apologies for multiple posts. I would even remove the at least/at most since it is confusing. You already have the "receive at least" in the previous box, so I would just add the following text as a footnote (not even a box):

* 1 DAI = 0.95 USDC
* 1 USDC = 1.052 DAI

My opinion is that you got it right in the telegram messages, which uses the above format.

**Comment by Rafanator** [comment]
I would suggest this: 

<img width="1131" alt="Screenshot 2020-03-19 at 16 08 04" src="https://user-images.githubusercontent.com/26544214/77082469-62e3e900-69fc-11ea-97ce-144a0542b6a6.png">

Reasoning: 

- Change in wording makes more sense, using terms like "at least" and 'minimum, max' is unusual in trading 
- The lower left box should auto-populate as it is weird for users to be able to input the same information in two separate boxes. 

What do you think guys?

**Comment by anxolin** [comment]
> Change in wording makes more sense, using terms like "at least" and 'minimum, max' is unusual in trading
Oko. Limit price sound good to me.

> The lower left box should auto-populate as it is weird for users to be able to input the same information in two separate boxes.

Agree, this is independent from this "issues", in fact, we are working in that right now.

> Also, make the box of the new auto-populated area white, so it is clear :)
We can try that in a PR and see the user's reaction. Maybe you are right and having fewer editable items is easier.


There's something that I still find odd in the interface. Let's keep this conversation going next week, I'm sure we can improve it a lot.

**Comment by anxolin** [comment]
One alternative proposal, that would require more changes but focus on:
* Anything that is not editable, is not an input
* Make the sell amount and price the most prominent part, and put them close together
* Make the price buyToken/sellToken the main price, and just inform the other as secondary as a label

![IMG_4168](https://user-images.githubusercontent.com/2352112/77173037-347b1200-6abf-11ea-83d6-806f187fa3de.JPG)

**Comment by Rafanator** [comment]
![borat](https://user-images.githubusercontent.com/26544214/77176733-cd605c00-6ac4-11ea-9491-8d9cfa7f5d2a.jpg)
