### ISSUE TITLE
Show connected wallet information when using Wallet Connect

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#735]
![image](https://user-images.githubusercontent.com/2352112/77059956-14245800-69d8-11ea-9704-7f3cb6bb24dc.png)

With this information we could personalize further the connected wallet, adding a custom icon.
We can make sure in the Wallet Connect telegram channel the best way to get this info, and how can the wallets report this "icons". 

We could use it also for the analytics.

**Comment by alfetopito** [comment]
keep open

**Comment by alfetopito** [comment]
@anxolin should we keep it?

**Comment by anxolin** [comment]
I think it's a nice to have, no important.
I just feel that it's easy to take this info and show a beautiful Gnosis Safe logo here:
![image](https://user-images.githubusercontent.com/2352112/88389015-eef48b80-cdb5-11ea-88db-fcd2a5516518.png)

You know the connected wallet if we use wallet connect

**Comment by anxolin** [comment]
Answer from Wallet Connect
https://t.me/walletconnect/12759

**Comment by alfetopito** [comment]
> Answer from Wallet Connect
> https://t.me/walletconnect/12759

Can you paste the answer here? It requires to join WalletConnect telegram's channel and also the msg might be removed at a later time, losing the reference.

**Comment by Velenir** [comment]
Closed by #1270
