### ISSUE TITLE
Allow to use the arrows keys in the token selector

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#741]
Normally, SELECTS allow to use the arrows keys (up/down key), to iterate over the options.

For example, in this example, as I user I would love to be able to select `TUSD` by:
- Input `us`. A filter is applied:
![image](https://user-images.githubusercontent.com/2352112/77163572-a4cd6780-6aae-11ea-925c-7f262970b494.png)

- Press down one time --> `USDT` is hightlighted:
![image](https://user-images.githubusercontent.com/2352112/77163534-8c5d4d00-6aae-11ea-9884-377cdad523f3.png)

- Press down another time --> `TUSD` is hightlighted
![image](https://user-images.githubusercontent.com/2352112/77163545-941cf180-6aae-11ea-8ec3-46aa91e2edee.png)

- Press INTRO --> `TUSD` is selected
![image](https://user-images.githubusercontent.com/2352112/77163325-207ae480-6aae-11ea-9aae-33e2429a505e.png)

**Comment by anxolin** [comment]
@Velenir this is what I meant here https://github.com/gnosis/dex-react/pull/736#issuecomment-601224218

**Comment by Velenir** [comment]
> Press INTRO --> `TUSD` is selected

![Intro](https://user-images.githubusercontent.com/5121491/77165076-aef96100-6ac2-11ea-9d15-f6683e5199ea.jpg)
