### ISSUE TITLE
Order Starts In (min)

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#750]
First issue is that if you set a value that is smaller than 15 it should show a validation error. It doesn't do that, and  it allows to press the "Set order parameter" in that state:

![image](https://user-images.githubusercontent.com/2352112/77413051-0e0aee80-6dbf-11ea-979a-e5af3d8c5d41.png)

Then, if you try to send the transaction, it won't, and it won't give the user any feedback.

I also find extrange how the input doesn't tell you anything if you for example set `14`, and the close the modal:
![image](https://user-images.githubusercontent.com/2352112/77413334-75c13980-6dbf-11ea-9d50-b6fbb6d6d267.png)

Then, if you  check the value (open the modal again), you'll see that the value was magically changed into `15`. 

One idea for the message, would be something like:
`Select a start time multiple of 5 since batches last 5min. Quick fix: Set 15min`

I'm sure we can come up with a better message anyways :)

**Comment by alfetopito** [comment]
Related https://github.com/gnosis/dex-react/issues/672

**Comment by W3stside** [comment]
> Related #672

thanks @alfetopito now I'm stuck in a loop
