### ISSUE TITLE
Pending orders show as filled

### ISSUE THREAD

**Issue by fleupold** [gnosis/dex-react#755]
Pending orders show 100% as filled although they haven't even been created yet.

<img width="476" alt="Screen Shot 2020-03-25 at 10 36 36" src="https://user-images.githubusercontent.com/1200333/77522478-999a8300-6e84-11ea-855b-e55464d3dbf4.png">

Tested on current staging.

**Comment by anxolin** [comment]
Thanks for notifying! we'll have a look into this.

**Comment by anxolin** [comment]
@fleupold can you confirm in which version you are testing this. Does it happen in the dev version to you?

**Comment by fleupold** [comment]
Just reproes on rinkeby v0.9.1 (I'm not sure what the URL for the dev version you are referring to is). Also, if you have no orders it doesn't show the pending one at all (if it's your first one)

Are you not able to reproduce it?

**Comment by anxolin** [comment]
Yes, that's an issue in the production version, was fixed long ago in our development version. I thought you meant it was also there. I'll share the dev version internally with you
