### ISSUE TITLE
Issues with the price

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#757]
I think we have some issue with the price suggestion:

**Sometimes we get NaN as the amount**
![image](https://user-images.githubusercontent.com/2352112/77537396-50efc380-6e9e-11ea-89ba-bc6dd4c78443.png)
If the price is not good, maybe we just default to `0 / Infinity` and show `0` in the receive amount

**Sometimes the price is not updated**

1. Select DAI-WETH. You'll get sth like `0.00746 / 134.0482` 
2. Change to DAI-GUSD. The amount don't change at all

**Comment by alfetopito** [comment]
> I think we have some issue with the price suggestion:
> 
> **Sometimes we get NaN as the amount**
> ![image](https://user-images.githubusercontent.com/2352112/77537396-50efc380-6e9e-11ea-89ba-bc6dd4c78443.png)
> If the price is not good, maybe we just default to `0 / Infinity` and show `0` in the receive amount
> 
> **Sometimes the price is not updated**
> 
>     1. Select DAI-WETH. You'll get sth like `0.00746 / 134.0482`
> 
>     2. Change to DAI-GUSD. The amount don't change at all

The issue is that GUSD doesn't have a value. It was never traded in the exchange it seems.
