### ISSUE TITLE
Sometimes there's a big delay showing the order in pending

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#759]
Observed behaviour:

1. A user submitted an order
2. The order didn't show up as pending right away, not even after some seconds
3. User was confused and refreshed several times (until it was mined) and showed up in the orders list

**Comment by alfetopito** [comment]
The pending order is created locally and stored in local storage once the tx is sent https://github.com/gnosis/dex-react/blob/develop/src/api/exchange/ExchangeApi.ts#L221.

If the page is refreshed before we got a chance to save it locally, it won't show up as pending.

I would guess there might have been a network delay causing the tx to take longer to be sent.

In fact, not able to reproduce on rinkeby using latest `develop` branch.

@anxo do you have more details to help reproduce this?
Did this happen many times?

**Comment by anxolin** [comment]
I saw it in one user session, @Rafanator claims he saw it on other sessions too.

I'll try now in mainnet. I'll post my result soon

**Comment by anxolin** [comment]
I can't reproduce, it must be a delay with the node. I sent several and there's no big delay.



>The pending order is created locally and stored in local storage once the tx is sent https://github.com/gnosis/dex-react/blob/develop/src/api/exchange/ExchangeApi.ts#L221.

Are you sure we persist it in "local storage" cause I did try to refresh while is in "pending" and it doesn't show in after refreshing

**Comment by alfetopito** [comment]
Actually, I couldn't find where pending txs are stored, just where they are loaded https://github.com/gnosis/dex-react/blob/67f578ce5f0187641297b158e86cca1e2010779d/src/reducers-actions/pendingOrders.ts#L77

@W3stside by any chance I missed something, or this was a bad merge that removed the saving part?

**Comment by anxolin** [comment]
@W3stside

**Comment by W3stside** [comment]
checking

**Comment by W3stside** [comment]
fixing

**Comment by anxolin** [comment]
@W3stside can you make sure we close this one?  You said there's an implemented PR that solves it, right?
