### ISSUE TITLE
react-select selects empty on click outside

### ISSUE THREAD

**Issue by Velenir** [gnosis/dex-react#778]
1. Open Token selector
2. Enter gibberish
3. Click outside of Token Selector
4. Panic

![ezgif-2-ddb9faecf5cd](https://user-images.githubusercontent.com/5121491/77753153-0145ff00-703a-11ea-8f58-7ae9e45d02c0.gif)

Happens because react-select changes final selection dynamically (on search, ArrowUp|Down, even hover) not on Enter/Confirmation or menu close

**Comment by alfetopito** [comment]
![](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.giphy.com%2Fmedia%2FGpxDDahLiDLJm%2Fgiphy.gif&f=1&nofb=1)
