### ISSUE TITLE
Allow to WRAP ether

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#789]
Proposal: Add a WRAP ether link here:
![image](https://user-images.githubusercontent.com/2352112/77943072-e6cf8800-72bc-11ea-9e22-e0ba956abde9.png)

That would open a modal:

![image](https://user-images.githubusercontent.com/2352112/77943374-69f0de00-72bd-11ea-893a-0b3445bb4ddd.png)

Ideally, we can add this also in the deposit page.

@biocom  @rafanator @c3rnst , what do you think?

**Comment by c3rnst** [comment]
I like that it's also added in the deposit page. 
Would you only show this when a user has selected WETH or when any sellToken is selected?
I think it's a good fix!

**Comment by Rafanator** [comment]
Love it!

 I agree with Chris that it would be nice if it is only there when the user selects WETH.

**Comment by anxolin** [comment]
Yes, only for WETH of course :)

**Comment by anxolin** [comment]
Proposal for the balances page:
![image](https://user-images.githubusercontent.com/2352112/78553594-d1e97c00-7809-11ea-8113-62f9ab1f9d8d.png)
