### ISSUE TITLE
Good to have: Order book

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#791]
We'll incorporate an order book as a pop up in the trade widget.

@fleupold will move the code to
https://6jxh4.codesandbox.io/

![image](https://user-images.githubusercontent.com/2352112/77945677-4e87d200-72c1-11ea-83b6-f3185808a6f7.png)

The original idea was to do a standalone app for this, but Felix prefers to add it as a page 

The original idea was:
* Make an independent project
* Have it’s own URL
* Expose a page with a minimal UI so anyone can use it with iframes. It would take the tokens as parameters
* Expose a normal UI, with the token selector: entry point for the web. Just minimal design, with a title, the selector, etc..
* We could try to make a popup with an iframe to it in Mesa, so it opens up the minimal UI for the selected token pair

I'm fine with Felix proposal too. We can make the placeholder for him: A blank page, with a blank widget where he'll encapsulate this graph. This component will have as parameter the 2 tokens. 
We could add the token selector in this page, to facilitate his development. So he would start with a blank component that has preselected 2 tokens.

Does this work?

**Comment by anxolin** [comment]
cc: @alfetopito @Velenir @W3stside

**Comment by fleupold** [comment]
Works for me. Let me know where to put the code. It can be found here: https://codesandbox.io/s/orderbook-centralized-czii9

**Comment by anxolin** [comment]
I've made this PR with the placeholders so you can add it there.
https://github.com/gnosis/dex-react/pull/800
