### ISSUE TITLE
Preselect, by default, all the tokens in the liquidity page

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#795]
@c3rnst you mentioned something about changing the message. Can you detail what we should do?

**Comment by c3rnst** [comment]
Let's pause this! Discussed it with Rafa and Anna that it will be better in light of discussion to pause this feature.

**Comment by c3rnst** [comment]
When coming to the liquidity page, please have 1) all tokens pre-selected, please 2) take out sUSD from the stablecoin liquidity. We can add it again once it's more solid around 1 or alternative if we have a functionality to adjust around a pricepoint in the future. 

Changes: 
1. in the first screen, change the first paragraph to read: 
"By (de)-selecting, define **at least two** stablecoins you want to include in your liquidity provision and believe are worth $1"
