### ISSUE TITLE
Improve state of the orders

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#797]
![image](https://user-images.githubusercontent.com/2352112/78025872-074e1f80-735b-11ea-8b57-e9e37f725bec.png)

Chris wrote in slack:
----------
We just had a good feedback with Martin and there is one change that should be prioritised over the adding-addresses to be included in this last pre-launch-sprint: 
It’s about seeing the status on submitted orders:

1. Transaction submitted --> Same as now.
2. Waiting to be included in the first batch, rather than saying Active, change to: “Active starting next batch: COUNTDOWN”
3. In the very first batch the order is part of: “Waiting for settlement: COUNTDOWN” (counting down the 4 minutes, not the 5).
4. From the second batch onwards, as usual: filled, partially filled and active. 
Regarding this, the two COUNTDOWNS are optionally and it would be good to see how cluttered it would look in the tables. Any chance, @Michel Bio could mock this up?
5. ~~Additionally, if not much work, fully filled orders should move to the tab “closed”.~~ (addressed on https://github.com/gnosis/dex-react/issues/907)
Do you know what we mean? Else, let’s have a quick chat about it.

Martin wrote:
------------------

A user comes to the exchange and wants to trade token A for B. They don’t want to place a order and see if it matches - they simply really want to have token B. So the idea is that you order should be matched immediately - if it is not matched immediatly the user want to submit the order again with a different price so that it gets matched.
Currently the user has no idea how long they need to wait untill they should expect a match. The answer is: 4-9 minutes after your order was mined. However - wether the order was mined at 4:59 ( last second of the batch) or at 5:01 (in the next batch) - you don’t see that. So it is really hard to get this info how long you should wait for a match.
The infos we are suggesting to add here should make it much easier to understand what is going on and when to expect a match.

**Comment by anxolin** [comment]
We have a small concern with this specific messages, because they might mislead the user.

** “Waiting for settlement: COUNTDOWN”**: Would probably make the user thing he'll have his orders match, when it only means, the order is being consider in the current batch, wait 4min until we see if there's a solution, and maybe your order will trade (maybe not)

**Comment by c3rnst** [comment]
I think *Waiting to find a match* is better? (from matching orders, which sounds also quite definitive) @Rafanator - is that good trading lingo or does it sound like tinder?

**Comment by Rafanator** [comment]
`Waiting for Match` -> I think less words might look better on the interface.

**Comment by alfetopito** [comment]
> `Waiting for Match` -> I think less words might look better on the interface.

That does fit better on the ui, but in my opinion still implies there will (for sure) be a match, we are just waiting for it.

**Comment by c3rnst** [comment]
Let's go with `Waiting for match` for this first iteration then. Let's get some user feedback but this can wait.

**Comment by anxolin** [comment]
If I understand correctly, the user will see for example this sequence if he don't trade in his first batch:

```
 Pending...
 Pending...
Active starting next batch: 4:55
Active starting next batch: 1:30
Active starting next batch: 1s
Waiting for match: 3min 59s
Waiting for match: 15s
Waiting for match: 5s
Waiting for match: 1s
Active
Active
....
```

**Comment by c3rnst** [comment]
Yes, your understanding is correct. It's about a user who wants to see a match right away and if they do not in the first batch, that means that they might need to change their price...

**Comment by anxolin** [comment]
@c3rnst, @alfetopito  made a proposal that I think improves a bit the message:

* **Active in next batch: 4:55**
* **Looking for match: 3min 59s**

```
 Pending...
 Pending...
Active in next batch: 4:55
Active in next batch: 1:30
Active in next batch: 1s
Looking for match: 3min 59s
Looking for match: 15s
Looking for match: 5s
Waiting for match: 1s
Active
Active
.... 3h later
Active
```

**Comment by c3rnst** [comment]
you mean without the "waiting", correct? This works perfectly, let's do it his way and wait for the next iteration to have user feedback.

**Comment by koeppelmann** [comment]
I'd still slightly prefer "pending settlement" or "pending solver submission" over "Looking for match" but fine either way.

**Comment by alfetopito** [comment]
I think "pending solver submission" is more clear than "pending settlement". I can change to that.

The concern is the same as with what I mentioned above. When I read `pending settlement` or `waiting for match`, I have the impression that there will be a match for sure.

This sets the wrong expectation leading to frustration after some time passes and still there's no match.
