### ISSUE TITLE
Firefox: small issues in balances page

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#798]
The label in the search box is out of place:
![image](https://user-images.githubusercontent.com/2352112/78036435-97479580-736a-11ea-9e1a-a22e58009442.png)

The table header backgroud is transparent and create this effect:
![image](https://user-images.githubusercontent.com/2352112/78036548-b7775480-736a-11ea-9193-cc8aa3abb096.png)

**Comment by W3stside** [comment]
I believe #655 fixes this as a side-effect

**Comment by anxolin** [comment]
I guess you mean #798

**Comment by alfetopito** [comment]
Can confirm, is fixed on https://dex.dev.gnosisdev.com/wallet
