### ISSUE TITLE
mesa.eth error connecting wallet (Android+Opera mobile)

### ISSUE THREAD

**Issue by ykplayer8** [gnosis/dex-react#828]
![image](https://user-images.githubusercontent.com/51191396/78459351-0bfb3680-76c1-11ea-85fe-7a60aba8c0d1.png)

**Comment by Velenir** [comment]
@ykplayer8 Can you try at https://dex.staging.gnosisdev.com/ and https://dex.dev.gnosisdev.com/

**Comment by Velenir** [comment]
Opera doesn't seem to connect over http
try https://mesa.eth.link

**Comment by ykplayer8** [comment]
works with any issues now
