### ISSUE TITLE
Should say 'Balances` instead of `Wallet` 

### ISSUE THREAD

**Issue by Rafanator** [gnosis/dex-react#830]
After signing the transaction to place liquidity, the page reads `Wallet page` instead of `Blances page` in the **What now?** section

<img width="422" alt="Screenshot 2020-04-06 at 12 55 02" src="https://user-images.githubusercontent.com/26544214/78551530-2985e880-7806-11ea-9d6c-fb0ef307c11b.png">

**Comment by Velenir** [comment]
This should have been closed automatically when #925 was merged as that one has `Closes` comment
What's wrong here? Is it because it was merged not into the default branch
@alfetopito @anxolin @W3stside

**Comment by alfetopito** [comment]
The PR says it could have been closed

![screenshot_2020-04-21_09-48-24](https://user-images.githubusercontent.com/43217/79891063-4c430000-83b5-11ea-91be-58f47491f861.png)

Can't tell why it didn't...
