### ISSUE TITLE
Add Order book

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#833]
Duplicate of #791

Add order into the trading page

- [X] Add Order book page: https://github.com/gnosis/dex-react/pull/800
- [X] Implement Order Book: https://github.com/gnosis/dex-react/pull/813
- [X] Add order book to Trading Page: #856, #850  (done, unmerged)

cc/ @biocom

**Comment by alfetopito** [comment]
https://github.com/gnosis/dex-react/issues/791 is a sub-task of this one and I believe is done.
