### ISSUE TITLE
Text for deposit button 

### ISSUE THREAD

**Issue by Rafanator** [gnosis/dex-react#867]
Hi @anxolin, Anna Chris and I agreed on the following text for the deposit button:

`The amount you deposit into your exchange wallet is your liquidity: at least deposit one stablecoin on ‘Balances’. `

Thank you!

**Comment by anxolin** [comment]
@biocom this is the a quick fix feedback BD gave to improve the Liquidity page.
The complaint was that users are not aware that they need to deposit before creating the liquidity orders.

What we discuss is please @Rafanator double confirm me this, you want this texts in both STEP 1, and STEP 2, highlighted, and with a link to the Wallet.

 Is this correct?
cc/ @c3rnst

**Comment by Rafanator** [comment]
Hi everyone! @c3rnst can you please confirm if @anxolin's message above is correct? 

Thanks!

**Comment by c3rnst** [comment]
Hi @Rafanator  - this is what was the conclusion in the meeting with yourself, Anna and myself. I believe the suggestion was a framed text at the bottom left of both screens.
