### ISSUE TITLE
Use PROD `dex-price-estimator` url

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#869]
We'll need to remember to update here the URL to the PRODUCTION one, since dev is more unreliable (downtime and resources) and PRO can have a balancer to be able to scale if necessary

_Originally posted by @anxolin in https://github.com/gnosis/dex-react/pull/834_

**Comment by anxolin** [comment]
@fleupold do we have URL for production?

**Comment by fleupold** [comment]
Not yet, but we can ask DevOps to deploy to prod on Tuesday.

**Comment by anxolin** [comment]
Okay, cool. Would you write us here when we should do the change?

**Comment by fleupold** [comment]
Thanks to @davidalbela the prod service https://dex-price-estimator.gnosis.io/ is up and running.

**Comment by alfetopito** [comment]
> https://dex-price-estimator.gnosis.io/

@fleupold I assume that's `mainnet` endpoint.
Is there one for `rinkeby` as well?

**Comment by fleupold** [comment]
It's https://dex-price-estimator.rinkeby.gnosis.io/

**Comment by W3stside** [comment]
Closes by #906
