### ISSUE TITLE
Decimal point and font-icons not shown

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#887]
tested on a virtualized windows 7 running last chrome version

## No decimal point:
![image](https://user-images.githubusercontent.com/2352112/79213043-cd941300-7e48-11ea-9572-f36802ab42a8.png)

![image](https://user-images.githubusercontent.com/2352112/79213169-ff0cde80-7e48-11ea-8c60-a5883ca9a9a1.png)

If I just check the balances in the Mac, I do see the decimal:
![image](https://user-images.githubusercontent.com/2352112/79213289-37acb800-7e49-11ea-9cf5-b6b0001a9b0b.png)

Interestingly, in the inputs it does add the decimal, so it must be just an issue with our formatter:
![image](https://user-images.githubusercontent.com/2352112/79213669-d9340980-7e49-11ea-8b0c-1e40a61a3db8.png)

## The font icons didn't load:
![image](https://user-images.githubusercontent.com/2352112/79212903-99205700-7e48-11ea-8a12-6f9283d75422.png)

**Comment by alfetopito** [comment]
Quick report, decimals on Win10 working fine for me.

**Comment by Velenir** [comment]
Can we close this?

Great work guys, can't believe the length we had to go to debug on Win

**Comment by anxolin** [comment]
Not critical, but I think we have the Font Family issue still unsolved

**Comment by W3stside** [comment]
is this windows specific? the font thing

**Comment by W3stside** [comment]
is this done?

**Comment by Velenir** [comment]
If we really want that unicode :skull: icon to be displayable everywhere regardless system fonts, we need to add a font with it to `font-family` explicitly, or switch the `Inter` font we use with one that has :skull: 
Or just make it an icon https://fontawesome.com/icons/skull?style=solid
Let's do the icon, easiest
