### ISSUE TITLE
Button disappears on hover on Liquidity page

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#900]
After placing liquidity orders, the button is disabled:

![screenshot_2020-04-14_10-13-01](https://user-images.githubusercontent.com/43217/79253752-96b60100-7e38-11ea-9c31-937a5df728ed.png)

When I hover with my mouse over it though, it is gone (cursor not displayed because of my screenshot tool)

![screenshot_2020-04-14_10-13-05](https://user-images.githubusercontent.com/43217/79253913-c8c76300-7e38-11ea-95ec-141b678323b3.png)

Happened on latest stating https://dex.dev.gnosisdev.com/liquidity (v0.11)

**Comment by anxolin** [comment]
Closed by #911
