### ISSUE TITLE
Orderbook amounts on `Light` theme are hard to read

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#901]
![screenshot_2020-04-14_11-17-55](https://user-images.githubusercontent.com/43217/79259504-ac7bf400-7e41-11ea-8f76-dfeaa1e40357.png)

Latest staging version `0.11` https://dex.dev.gnosisdev.com/

**Comment by Velenir** [comment]
![dex dev gnosisdev com_trade_DAI-USDC_sell=0 price=1 01548 from= expires=2880](https://user-images.githubusercontent.com/5121491/79313012-676ec500-7f08-11ea-9241-7fefb9a37e48.png)

still kinda hard to see after that PR

**Comment by W3stside** [comment]
it's fine for me, closing
