### ISSUE TITLE
Move filled orders to `Closed` orders tab

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#907]
Orders which have the display text `Filled` should not be displayed in the `Active` orders tab.
Instead, they should be displayed into the `Closed` orders tab.

Somewhat related to #797

**Comment by anxolin** [comment]
I would have swear I created already this issue, but now I don't find it. I had a picture for it :) 

The highlighted row should be in the CLOSED tab:
<img width="937" alt="Screenshot at Apr 09 12-20-49" src="https://user-images.githubusercontent.com/2352112/79282845-79277c80-7eb6-11ea-8a4f-e4fa7bc2f7c6.png">
