### ISSUE TITLE
Order is filled but interface does not show it

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#909]
Once the page is refreshed though, the order is displayed as filled.

---

I suspect the reason is due to order caching.

Since on every new block we only query for new orders from the last point we checked, we'll never know the order has been matched.

See https://github.com/gnosis/dex-react/blob/develop/src/hooks/useOrders.ts#L91

We might need to either lose the optimization or maybe subscribe to order placement/matching events and update only the ones that changed.

**Comment by Velenir** [comment]
Should we consider this fixed?

**Comment by alfetopito** [comment]
Well, we did a temporary fix...
Should we have a long term fix updating orders by listening to trade events?

**Comment by Velenir** [comment]
I'm not sure that kind of subscription will even work with some mobile wallets. Need to check

**Comment by alfetopito** [comment]
Another improvement I thought about (considering my horrible first fix attempt) that might be useful to avoid flickering when we fetch orders from start is to have the option to merge the current list of orders.

I'm thinking about moving the filtering to the global state, and there (when merging) update the existing orders, removing ones that have potentially been cancelled.

This way, the list is always constant, while only modified orders are updated/removed.

What do ya think?

**Comment by alfetopito** [comment]
Since this issue is fixed, I'll close it.

Opened a new one to address what I have in mind https://github.com/gnosis/dex-react/issues/948
