### ISSUE TITLE
Review gnosis icon in trust wallet

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#913]
Review gnosis icon in trust wallet

**Comment by alfetopito** [comment]
Asked for new logos for OWL and GNO on [`design requests`](https://gnosisinc.slack.com/archives/C6ZQKD08N) slack channel

**Comment by alfetopito** [comment]
PRs created. Waiting finance team to pay the merge fee.

https://github.com/trustwallet/assets/pull/2070
https://github.com/trustwallet/assets/pull/2071

**Comment by anxolin** [comment]
@alfetopito as said in planning, we have to insist on Steven to pay the fee

**Comment by alfetopito** [comment]
New PRs:

trustwallet/assets#2137
trustwallet/assets#2138
