### ISSUE TITLE
Review layout for tokens with loooooooooooooooooooooong names

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#941]
https://gnosisinc.slack.com/archives/CSGLUC1BN/p1587145793025300

![image](https://user-images.githubusercontent.com/2352112/79602823-811c3200-80eb-11ea-8d6f-c0f1cf11f310.png)

**Comment by alfetopito** [comment]
Orders are not thaaat bad. You should see how the trade widget looks like with this sort of token: https://github.com/gnosis/dex-react/pull/924#issue-403994694.

That IS bad...
