### ISSUE TITLE
Link to FAQ is broken on Wallet Withdrawal page

### ISSUE THREAD

**Issue by lookfirst** [gnosis/dex-react#942]
Looks like it should be a `<Link>` tag instead...

https://github.com/gnosis/dex-react/blob/f3e6e25798c7fc7fb7c311bfec237f3a1a74a404/src/components/DepositWidget/Form.tsx#L115

![image](https://user-images.githubusercontent.com/85355/79701572-079f5380-8253-11ea-9177-4e6feb4dad33.png)

**Comment by alfetopito** [comment]
Thank you for reporting. We'll double check :)
