### ISSUE TITLE
Smarter decimal formatting

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#943]
![image](https://user-images.githubusercontent.com/2352112/79727599-e5f2aa80-82ec-11ea-92a7-c97f2bde054e.png)

When we display some numbers, we show only a few decimals while the precisions are bigger. We should have smarter ways of representing decimals.

Also applies to the balances, where for exmple, if you have just a few dollars in WBTC you'll still see `0.0000`

**Comment by W3stside** [comment]
Looking for feedback but I would like to go ahead with the Gnosis Safe [formatting system for numbers](https://github.com/gnosis/safe/blob/a87d5d8af99a4d6fd35424a7e0743379a44bf9a8/archive/specs/common/format_amounts.rst) 

`i.e`:

1. Cut off after the 5th decimal, no matter how many decimals there are: 0.12345
2. Remove trailing zeroes, i.e. display 0.10000 as 0.1.
3. Represent number via million/billions abbrv. `e.g` 1.2M, 1.2B, 1.2T <-- NOT thousands (K) like Safe
  a. k, M, B, T should be localized

Use "tap to show amount" on mobile - user taps amount and we show full, un-truncated amt on mobile only

**Comment by W3stside** [comment]
Will follow up with prototype of `tap-to-show` amount screenshots

**Comment by anxolin** [comment]
Yes, it's a good idea to implement some kind of smart formatting strategies that depends on how big the numbers are. Makes sense to me be consistent to Gnosis Safe in this matter too.

Maybe ask to German/Lukas if they have an implementation already you can bring to the project.

Lastly, the tap-to-show, please don't do that in the same PR, I think it's good to try it out, but this was part of a quite long discussion, it's better to take it to a different issue/PR.

**Comment by W3stside** [comment]
Recommend using:

https://github.com/gnosis/safe-react/blob/b7eb988d9f7b3538b26cdbf05a90edac01883d02/src/logic/tokens/utils/formatAmount.js
