### ISSUE TITLE
Allow to select the maximum slippage

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#952]
Consider making the price estimation more tight (don't subtract any value on top of the fees), and then offer these options:

![image](https://user-images.githubusercontent.com/2352112/80074464-7b8a7600-8549-11ea-8872-835682ed5784.png)

`0.5%` would be the default option and pre-selected, so the price inputs it's already auto-filled with this value.

@koeppelmann, this percentages goes on top of the fees, right? because the `actual price - 0.2%` is the price that would make a solution feasible, so that would be the price at `0%` (which we don't offer)

Let's see the proposal with an example:
* An user wants to change `100 DAI for USDC`
* There's an order of `100 USDC for 100 DAI` in the order book
* The price estimation will return `99.8`

The UI will offer:
* 0.1% = 99.7002
* 0.5% (default) = 99.301
* 1% = 98.802

For the custom field, 0% would be a valid value, but also negative amounts, that would give you a better price, but the order won't probably be fulfilled soon.

cc/ @fleupold @alfetopito @c3rnst

**Comment by W3stside** [comment]
is this in the liquidity page or on all trade pages?

**Comment by W3stside** [comment]
`Est 3`

**Comment by anxolin** [comment]
> is this in the liquidity page or on all trade pages?

I think we talked it in the chat. But for leaving it here too ---> Only trade page

**Comment by anxolin** [comment]
@W3stside can we close by --> merge just the component and do not include it in the trade widget?
