### ISSUE TITLE
Bundle size: webpack

### ISSUE THREAD

**Issue by alfetopito** [gnosis/dex-react#97]
Bundle size: First review and fixes

**Estimation:** 4.5 (as of Sprint 9)

**Comment by anxolin** [comment]
A bit of background, apparently the bundle right now is arround 5MB. The idea is just doing a basic review on why is so big with so few libs. Probably a dependency that shouldn't be there is being pooled.

We have to confirm that this 5MB was in the minimized version, and we do actually the tree shaking for deleting dead code. If we see something quick/basic that we can do, like load some core parts first and then have the optional parts run on demand. Also, maybe, if it's worth it, separating the vendor JS from the app so it can be cached between versions of our app.

**Comment by anxolin** [comment]
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia2.giphy.com%2Fmedia%2F110gqI69qjVAkM%2Fgiphy.gif&token=fat" data-gitmeme-token="fat"><img src="https://media2.giphy.com/media/110gqI69qjVAkM/giphy.gif" title="Created by gitme.me with /fat"/></a>

**Comment by alfetopito** [comment]
Check how Mock stuff is loaded: https://github.com/gnosis/dex-react/pull/327#discussion_r359981480

**Comment by anxolin** [comment]
Something to take into account in this ISSUE too is:
- Make sure that when we load the ABIs, we don't add all the truffle contract info ---> huge
- Make sure none of the mock data is included and webpack removes that
- We don't include unused parts of code or libraries
- We don't include internationalization libraries from third party applications
- And of course study how to load our modules, maybe vendor, main, and then one async module per page... (study)

**Comment by Velenir** [comment]
Through better tree-shaking, dependency changes and other obscure magic we are down 1/3 of bundle size.

Next step -- Lazy loading #485
