### ISSUE TITLE
Expanded OrdersWidget on Trade page breaks when media queries kick in

### ISSUE THREAD

**Issue by W3stside** [gnosis/dex-react#988]
To test
1. in web mode expand the Orders Widget using the expander button
2. resize window
3. observe the catastrophe

**Comment by anxolin** [comment]
True:
![image](https://user-images.githubusercontent.com/2352112/80960847-fab16100-8e09-11ea-8395-3f89a8b4f877.png)

**Comment by anxolin** [comment]
@W3stside what do we do with this issue?
