### ISSUE TITLE
Liquidity Orders Widget

### ISSUE THREAD

**Issue by W3stside** [gnosis/dex-react#989]
One UX review was the lack of seeing current liquidity orders inside Liquidity page - consider adding an OrdersWidget inside to allow users to see without changing pages

Closed
![Screenshot from 2020-05-02 15-24-40](https://user-images.githubusercontent.com/21335563/80865350-25c07700-8c89-11ea-93b1-02dddf8dc8f2.png)

Open
![Screenshot from 2020-05-02 15-24-56](https://user-images.githubusercontent.com/21335563/80865360-2d801b80-8c89-11ea-9842-7739818f38be.png)

**Comment by anxolin** [comment]
Great! I agree this is something we should do.

I'm not convinced about showing the orders collapsed. It fees weird to have the banner below the orders, and that drop down button. Anyways, we can reiterate in this idea.

Anna has some ideas also for the liquidity page that goes in this direction.

My view is that we should also try to make a more compact summary of your strategy, making it easier to add or modify an strategy by adding/removing a token, or changing the spread.

Showing 42 orders is not super practical for the users.

**Comment by alfetopito** [comment]
Kind of going in this direction on https://github.com/gnosis/dex-react/pull/1111

**Comment by alfetopito** [comment]
Done on #1111
