### ISSUE TITLE
Browser freeze when changing to Kovan

### ISSUE THREAD

**Issue by anxolin** [gnosis/dex-react#996]
It looks like an infinite loop.

The only supported networks are mainnet and rinkeby. If the user is in an unsupported network, we should show a clarifying message

**Comment by alfetopito** [comment]
Duplicate of https://github.com/gnosis/dex-react/issues/283

**Comment by anxolin** [comment]
> Duplicate of #283

Ohh, right. I thought that one was to control it better and show a message to the user so I created this one with more priority (see the double label :P ) cause it's breaking the app and freezing the browser

Closing. Thx!!!
